-- Auditoria de catalogos, SOLO LECTURA. Ejecutar con rol de administracion.
-- No invoca RPCs de negocio, no lee tokens ni provisiona claves.
-- Presencia de objetos NO demuestra definicion vigente ni aplicacion integral.
BEGIN TRANSACTION READ ONLY;

SELECT current_database() AS database_name,
       to_regclass('supabase_migrations.schema_migrations') AS migration_history_table;
-- Si la tabla anterior existe, consultar por separado:
-- SELECT version, name FROM supabase_migrations.schema_migrations ORDER BY version;
-- No se ejecuta aqui para permitir instalaciones sin historial de Supabase CLI.

WITH expected(migration, kind, schema_name, object_name) AS (VALUES
  ('20260611144100_create_user_google_credentials.sql', 'TABLE', 'public', 'user_google_credentials'),
  ('20260723170000_create_render_worker_job_recovery_states.sql', 'TABLE', 'public', 'render_worker_job_recovery_states'),
  ('20260905100000_harden_sound_effect_asset_integrity.sql', 'FUNCTION', 'public', 'prevent_ready_sound_effect_binary_mutation'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'FUNCTION', 'public', 'claim_scorm_import_job'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'FUNCTION', 'public', 'heartbeat_scorm_import_job'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'FUNCTION', 'public', 'create_scorm_import_artifact'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'FUNCTION', 'public', 'reset_scorm_material_projection'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'TABLE', 'public', 'heygen_provider_assets'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'TABLE', 'public', 'heygen_catalog_sync_runs'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'FUNCTION', 'public', 'reconcile_heygen_catalog_snapshot'),
  ('20260920004500_reconcile_heygen_core_catalog.sql', 'FUNCTION', 'public', 'reconcile_heygen_core_catalog_snapshot'),
  ('20260920011500_reconcile_private_heygen_catalog.sql', 'FUNCTION', 'public', 'reconcile_heygen_private_catalog_snapshot'),
  ('20260920020000_make_heygen_catalog_visibility_durable.sql', 'TABLE', 'public', 'heygen_catalog_exclusions'),
  ('20260920020000_make_heygen_catalog_visibility_durable.sql', 'FUNCTION', 'public', 'set_heygen_catalog_preset_archived'),
  ('20260920020000_make_heygen_catalog_visibility_durable.sql', 'FUNCTION', 'public', 'reconcile_heygen_private_catalog_snapshot'),
  ('20260921120000_add_audio_processing_job_leases.sql', 'FUNCTION', 'public', 'claim_audio_processing_jobs'),
  ('20260921120000_add_audio_processing_job_leases.sql', 'FUNCTION', 'public', 'complete_audio_processing_job'),
  ('20260921120000_add_audio_processing_job_leases.sql', 'FUNCTION', 'public', 'fail_audio_processing_job'),
  ('20260922120000_route_audio_processing_jobs_by_profile.sql', 'FUNCTION', 'public', 'claim_audio_processing_jobs_by_profile'),
  ('20260922120000_route_audio_processing_jobs_by_profile.sql', 'FUNCTION', 'public', 'claim_audio_processing_jobs'),
  ('20260923090000_create_asset_access_audit_events.sql', 'TABLE', 'public', 'asset_access_audit_events'),
  ('20260929120000_record_hyperframes_final_video_checksum.sql', 'FUNCTION', 'public', 'record_hyperframes_final_video_checksum'),
  ('20260929120000_record_hyperframes_final_video_checksum.sql', 'FUNCTION', 'private', 'protect_hyperframes_final_video_integrity'),
  ('20260930120000_queue_hyperframes_video_integrity.sql', 'TABLE', 'private', 'hyperframes_video_integrity_jobs'),
  ('20260930120000_queue_hyperframes_video_integrity.sql', 'FUNCTION', 'private', 'enqueue_hyperframes_video_integrity'),
  ('20260930120000_queue_hyperframes_video_integrity.sql', 'FUNCTION', 'public', 'claim_hyperframes_video_integrity_job'),
  ('20260930120000_queue_hyperframes_video_integrity.sql', 'FUNCTION', 'public', 'finish_hyperframes_video_integrity_job'),
  ('20260930130000_persist_visual_conformance_evidence.sql', 'TABLE', 'private', 'hyperframes_visual_conformance_evidence'),
  ('20260930130000_persist_visual_conformance_evidence.sql', 'FUNCTION', 'public', 'record_hyperframes_visual_conformance_evidence'),
  ('20260930140000_read_visual_conformance_evidence.sql', 'FUNCTION', 'public', 'read_hyperframes_visual_conformance_evidence'),
  ('20260930150000_persist_audio_conformance_evidence.sql', 'TABLE', 'private', 'hyperframes_audio_conformance_evidence'),
  ('20260930150000_persist_audio_conformance_evidence.sql', 'FUNCTION', 'public', 'record_hyperframes_audio_conformance_evidence'),
  ('20260930150000_persist_audio_conformance_evidence.sql', 'FUNCTION', 'public', 'read_hyperframes_audio_conformance_evidence'),
  ('20260930160000_queue_full_conformance_reports.sql', 'TABLE', 'private', 'hyperframes_conformance_jobs'),
  ('20260930160000_queue_full_conformance_reports.sql', 'FUNCTION', 'private', 'enqueue_hyperframes_full_conformance'),
  ('20260930160000_queue_full_conformance_reports.sql', 'FUNCTION', 'public', 'claim_hyperframes_conformance_job'),
  ('20260930160000_queue_full_conformance_reports.sql', 'FUNCTION', 'public', 'renew_hyperframes_conformance_job'),
  ('20260930160000_queue_full_conformance_reports.sql', 'FUNCTION', 'public', 'finish_hyperframes_conformance_job'),
  ('20260930160000_queue_full_conformance_reports.sql', 'FUNCTION', 'public', 'read_hyperframes_conformance_report'),
  ('20261001120000_extend_chunked_audio_evidence.sql', 'FUNCTION', 'public', 'record_hyperframes_audio_conformance_evidence'),
  ('20261001130000_persist_playback_audio_evidence.sql', 'FUNCTION', 'public', 'record_hyperframes_audio_conformance_evidence'),
  ('20261001140000_persist_event_visual_conformance_evidence.sql', 'TABLE', 'private', 'hyperframes_event_visual_conformance_evidence'),
  ('20261001140000_persist_event_visual_conformance_evidence.sql', 'FUNCTION', 'public', 'record_hyperframes_event_visual_conformance_evidence'),
  ('20261001140000_persist_event_visual_conformance_evidence.sql', 'FUNCTION', 'public', 'read_hyperframes_event_visual_conformance_evidence'),
  ('20261001150000_persist_event_batch_measurements.sql', 'TABLE', 'private', 'hyperframes_event_batch_measurements'),
  ('20261001150000_persist_event_batch_measurements.sql', 'FUNCTION', 'public', 'record_hyperframes_event_batch_measurement'),
  ('20261001150000_persist_event_batch_measurements.sql', 'FUNCTION', 'public', 'read_hyperframes_event_batch_measurement'),
  ('20261001160000_bind_event_summary_to_job_finalization.sql', 'FUNCTION', 'private', 'verify_hyperframes_event_summary'),
  ('20261001160000_bind_event_summary_to_job_finalization.sql', 'FUNCTION', 'private', 'verify_hyperframes_deck_summary'),
  ('20261001160000_bind_event_summary_to_job_finalization.sql', 'FUNCTION', 'public', 'finish_hyperframes_conformance_job'),
  ('20261002160000_bind_controlled_execution_summary.sql', 'FUNCTION', 'public', 'finish_hyperframes_conformance_job'),
  ('20261003160000_bind_conformance_report_attempt.sql', 'FUNCTION', 'public', 'finish_hyperframes_conformance_job'),
  ('20261003170000_composition_render_execution_authority.sql', 'TABLE', 'private', 'composition_render_supervisor_keys'),
  ('20261003170000_composition_render_execution_authority.sql', 'TABLE', 'private', 'composition_render_executions'),
  ('20261003170000_composition_render_execution_authority.sql', 'FUNCTION', 'private', 'guard_render_supervisor_key_identity'),
  ('20261003170000_composition_render_execution_authority.sql', 'FUNCTION', 'private', 'composition_render_execution_context'),
  ('20261003170000_composition_render_execution_authority.sql', 'FUNCTION', 'public', 'issue_composition_render_execution'),
  ('20261003170000_composition_render_execution_authority.sql', 'FUNCTION', 'public', 'read_composition_render_execution'),
  ('20261003170000_composition_render_execution_authority.sql', 'FUNCTION', 'public', 'consume_composition_render_execution'),
  ('20261003170000_composition_render_execution_authority.sql', 'FUNCTION', 'public', 'cancel_composition_render_execution'),
  ('20261004160000_recover_consumed_render_execution.sql', 'FUNCTION', 'public', 'read_consumed_composition_render_execution'),
  ('20261004170000_finalize_controlled_composition_render.sql', 'FUNCTION', 'public', 'finalize_controlled_composition_render'),
  ('20261005160000_controlled_render_upload_sessions.sql', 'TABLE', 'private', 'composition_render_upload_sessions'),
  ('20261005160000_controlled_render_upload_sessions.sql', 'FUNCTION', 'private', 'assert_controlled_render_upload_authority'),
  ('20261005160000_controlled_render_upload_sessions.sql', 'FUNCTION', 'public', 'read_controlled_render_upload'),
  ('20261005160000_controlled_render_upload_sessions.sql', 'FUNCTION', 'public', 'save_controlled_render_upload'),
  ('20261005170000_check_controlled_render_video_authority.sql', 'FUNCTION', 'public', 'check_controlled_render_video_authority'),
  ('20261005170000_check_controlled_render_video_authority.sql', 'FUNCTION', 'public', 'finish_hyperframes_video_integrity_job'),
  ('20261005180000_controlled_render_worker_queue.sql', 'TABLE', 'private', 'controlled_render_worker_jobs'),
  ('20261005180000_controlled_render_worker_queue.sql', 'FUNCTION', 'public', 'enqueue_controlled_render_worker_job'),
  ('20261005180000_controlled_render_worker_queue.sql', 'FUNCTION', 'public', 'claim_controlled_render_worker_job'),
  ('20261005180000_controlled_render_worker_queue.sql', 'FUNCTION', 'public', 'renew_controlled_render_worker_job'),
  ('20261005180000_controlled_render_worker_queue.sql', 'FUNCTION', 'public', 'finish_controlled_render_worker_job'),
  ('20261005190000_controlled_render_worker_fences.sql', 'FUNCTION', 'private', 'assert_controlled_render_worker_lease'),
  ('20261005190000_controlled_render_worker_fences.sql', 'FUNCTION', 'public', 'issue_composition_render_execution'),
  ('20261005190000_controlled_render_worker_fences.sql', 'FUNCTION', 'public', 'consume_composition_render_execution'),
  ('20261005190000_controlled_render_worker_fences.sql', 'FUNCTION', 'public', 'cancel_composition_render_execution'),
  ('20261005190000_controlled_render_worker_fences.sql', 'FUNCTION', 'public', 'read_controlled_render_upload'),
  ('20261005190000_controlled_render_worker_fences.sql', 'FUNCTION', 'public', 'save_controlled_render_upload'),
  ('20261005190000_controlled_render_worker_fences.sql', 'FUNCTION', 'public', 'finalize_controlled_composition_render'),
  ('20261005200000_html_editing_revision_store.sql', 'TABLE', 'private', 'composition_html_templates'),
  ('20261005200000_html_editing_revision_store.sql', 'TABLE', 'private', 'composition_html_revisions'),
  ('20261005200000_html_editing_revision_store.sql', 'FUNCTION', 'private', 'assert_html_editing_actor'),
  ('20261005200000_html_editing_revision_store.sql', 'FUNCTION', 'private', 'html_editing_grants'),
  ('20261005200000_html_editing_revision_store.sql', 'FUNCTION', 'public', 'register_html_editing_template'),
  ('20261005200000_html_editing_revision_store.sql', 'FUNCTION', 'public', 'read_html_editing_revision'),
  ('20261005200000_html_editing_revision_store.sql', 'FUNCTION', 'public', 'revoke_html_editing_template'),
  ('20261005210000_append_html_editing_native_document.sql', 'FUNCTION', 'public', 'append_html_editing_revision'),
  ('20261005220000_read_exact_html_editing_compilation.sql', 'FUNCTION', 'public', 'read_html_editing_compilation'),
  ('20261005230000_controlled_html_editing_authority.sql', 'FUNCTION', 'public', 'read_controlled_render_html_editing_authority'),
  ('20261006000000_html_snapshot_resource_validation.sql', 'FUNCTION', 'private', 'html_snapshot_resource_bindings'),
  ('20261006010000_commit_html_editing_snapshot.sql', 'TABLE', 'private', 'composition_html_snapshot_intents'),
  ('20261006010000_commit_html_editing_snapshot.sql', 'TABLE', 'private', 'composition_html_snapshot_operations'),
  ('20261006010000_commit_html_editing_snapshot.sql', 'FUNCTION', 'public', 'commit_html_editing_snapshot'),
  ('20261006020000_read_html_snapshot_operation.sql', 'FUNCTION', 'public', 'read_html_editing_snapshot_operation'),
  ('20261006030000_html_snapshot_durable_intents.sql', 'FUNCTION', 'public', 'record_html_editing_snapshot_intent'),
  ('20261006030000_html_snapshot_durable_intents.sql', 'FUNCTION', 'public', 'read_html_editing_snapshot_intent'),
  ('20261006040000_narrative_extraction_atomic_receipts.sql', 'TABLE', 'public', 'narrative_extraction_receipts'),
  ('20261006040000_narrative_extraction_atomic_receipts.sql', 'FUNCTION', 'public', 'read_narrative_extraction_receipt'),
  ('20261006040000_narrative_extraction_atomic_receipts.sql', 'FUNCTION', 'public', 'commit_narrative_voice_extraction'),
  ('20261006050000_html_editing_bootstrap_registration.sql', 'FUNCTION', 'public', 'register_html_editing_template_v2'),
  ('20261006060000_read_html_editing_bootstrap_context.sql', 'FUNCTION', 'public', 'read_html_editing_bootstrap_context'),
  ('20261006070000_read_html_editing_restore_revision.sql', 'FUNCTION', 'public', 'read_html_editing_restore_revision'),
  ('20261006080000_html_editing_operation_receipts.sql', 'TABLE', 'private', 'composition_html_operation_receipts'),
  ('20261006080000_html_editing_operation_receipts.sql', 'FUNCTION', 'public', 'commit_html_editing_operation'),
  ('20261006080000_html_editing_operation_receipts.sql', 'FUNCTION', 'public', 'read_html_editing_operation'),
  ('20261006090000_html_editing_initialization_receipts.sql', 'TABLE', 'private', 'composition_html_initialization_receipts'),
  ('20261006090000_html_editing_initialization_receipts.sql', 'FUNCTION', 'public', 'commit_html_editing_initialization_operation'),
  ('20261006090000_html_editing_initialization_receipts.sql', 'FUNCTION', 'public', 'read_html_editing_initialization_operation'),
  ('20261006100000_narrative_fragment_resource_guards.sql', 'FUNCTION', 'private', 'validate_narrative_fragment_resources'),
  ('20261006110000_narrative_fragment_caption_guard.sql', 'FUNCTION', 'private', 'validate_narrative_fragment_caption'),
  ('20261006120000_narrative_fragment_clip_guard.sql', 'FUNCTION', 'private', 'validate_narrative_fragment_clip'),
  ('20261006130000_narrative_fragment_selection_guard.sql', 'FUNCTION', 'private', 'narrative_fragment_selected_clips'),
  ('20261006140000_narrative_fragment_document_delta.sql', 'FUNCTION', 'private', 'narrative_fragment_document_delta'),
  ('20261006150000_narrative_fragment_atomic_receipts.sql', 'TABLE', 'public', 'narrative_fragment_receipts'),
  ('20261006150000_narrative_fragment_atomic_receipts.sql', 'FUNCTION', 'public', 'read_narrative_fragment_receipt'),
  ('20261006150000_narrative_fragment_atomic_receipts.sql', 'FUNCTION', 'public', 'commit_narrative_fragment'),
  ('20261008100000_html_editing_legacy_adoption.sql', 'TABLE', 'private', 'composition_html_legacy_candidates'),
  ('20261008100000_html_editing_legacy_adoption.sql', 'TABLE', 'private', 'composition_html_legacy_adoption_receipts'),
  ('20261008100000_html_editing_legacy_adoption.sql', 'FUNCTION', 'public', 'record_html_editing_legacy_candidate'),
  ('20261008100000_html_editing_legacy_adoption.sql', 'FUNCTION', 'public', 'read_html_editing_legacy_candidate'),
  ('20261008100000_html_editing_legacy_adoption.sql', 'FUNCTION', 'public', 'revoke_html_editing_legacy_candidate'),
  ('20261008100000_html_editing_legacy_adoption.sql', 'FUNCTION', 'public', 'commit_html_editing_legacy_adoption'),
  ('20261008100000_html_editing_legacy_adoption.sql', 'FUNCTION', 'public', 'read_html_editing_legacy_adoption_operation'),
  ('20261008190000_bind_selected_event_measurements.sql', 'FUNCTION', 'public', 'record_hyperframes_selected_event_batch_measurement'),
  ('20261008190000_bind_selected_event_measurements.sql', 'FUNCTION', 'public', 'read_hyperframes_selected_event_batch_measurement'),
  ('20261008200000_support_silent_conformance_reports.sql', 'FUNCTION', 'private', 'verify_hyperframes_silent_audio_report'),
  ('20261008210000_reserve_conformance_render_inputs.sql', 'TABLE', 'private', 'hyperframes_conformance_render_reservations'),
  ('20261008210000_reserve_conformance_render_inputs.sql', 'FUNCTION', 'public', 'register_hyperframes_conformance_render_reservation'),
  ('20261008210000_reserve_conformance_render_inputs.sql', 'FUNCTION', 'public', 'read_hyperframes_conformance_render_reservation'),
  ('20261008210000_reserve_conformance_render_inputs.sql', 'FUNCTION', 'public', 'finish_hyperframes_conformance_job'),
  ('20261008220000_defer_conformance_render_reservations.sql', 'TABLE', 'private', 'hyperframes_conformance_render_outbox'),
  ('20261008220000_defer_conformance_render_reservations.sql', 'FUNCTION', 'private', 'attach_hyperframes_conformance_render_outbox'),
  ('20261008220000_defer_conformance_render_reservations.sql', 'FUNCTION', 'public', 'stage_hyperframes_conformance_render_reservation'),
  ('20261008220000_defer_conformance_render_reservations.sql', 'FUNCTION', 'private', 'attach_conformance_outbox_after_job_insert'),
  ('20261009010000_provided_syllabus_imports.sql', 'TABLE', 'public', 'syllabus_source_documents'),
  ('20261009010000_provided_syllabus_imports.sql', 'TABLE', 'public', 'syllabus_imports'),
  ('20261009010000_provided_syllabus_imports.sql', 'TABLE', 'public', 'syllabus_import_revisions'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'guard_syllabus_document_quota'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'guard_syllabus_import_quota'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'guard_syllabus_import_original'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'version_syllabus_content'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'invalidate_syllabus_dependents'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'transition_syllabus_import'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'guard_provided_syllabus_fidelity'),
  ('20261009010000_provided_syllabus_imports.sql', 'FUNCTION', 'public', 'guard_provided_syllabus_dependency'),
  ('20261009090000_fix_voice_audio_processing_compatibility.sql', 'FUNCTION', 'public', 'complete_audio_processing_job'),
  ('20261009090000_fix_voice_audio_processing_compatibility.sql', 'FUNCTION', 'public', 'claim_audio_processing_jobs_by_profile')
)
SELECT e.*, CASE WHEN e.kind = 'TABLE' THEN
  EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
          WHERE n.nspname=e.schema_name AND c.relname=e.object_name AND c.relkind IN ('r','p'))
  ELSE EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
               WHERE n.nspname=e.schema_name AND p.proname=e.object_name AND p.prokind='f') END AS exists_in_catalog
FROM expected e ORDER BY migration, kind, schema_name, object_name;

WITH expected(migration, table_name, column_name) AS (VALUES
  ('20260905100000_harden_sound_effect_asset_integrity.sql', 'video_composition_sound_effect_assets', 'source_storage_bucket'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'scorm_imports', 'processing_attempt'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'scorm_imports', 'processing_started_at'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'scorm_imports', 'processing_heartbeat_at'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'scorm_imports', 'lease_expires_at'),
  ('20260910120000_durable_scorm_import_jobs.sql', 'scorm_imports', 'updated_at'),
  ('20260910140000_add_operational_correlation_ids.sql', 'scorm_imports', 'correlation_id'),
  ('20260910140000_add_operational_correlation_ids.sql', 'publication_requests', 'correlation_id'),
  ('20260919120000_harden_organization_fonts_for_video.sql', 'organization_slide_fonts', 'checksum_sha256'),
  ('20260919120000_harden_organization_fonts_for_video.sql', 'organization_slide_fonts', 'file_size_bytes'),
  ('20260919120000_harden_organization_fonts_for_video.sql', 'organization_slide_fonts', 'mime_type'),
  ('20260919120000_harden_organization_fonts_for_video.sql', 'organization_slide_fonts', 'status'),
  ('20260919120000_harden_organization_fonts_for_video.sql', 'organization_slide_fonts', 'storage_bucket'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_workspace_connections', 'last_sync_request_id'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_avatar_presets', 'provider_state'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_avatar_presets', 'ownership'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_avatar_presets', 'last_seen_at'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_avatar_presets', 'missing_since'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_voice_presets', 'provider_state'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_voice_presets', 'ownership'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_voice_presets', 'last_seen_at'),
  ('20260919140000_reconcile_heygen_workspace_catalog.sql', 'heygen_voice_presets', 'missing_since'),
  ('20260921120000_add_audio_processing_job_leases.sql', 'production_jobs', 'audio_processing_lease_token'),
  ('20260921120000_add_audio_processing_job_leases.sql', 'production_jobs', 'audio_processing_lease_expires_at'),
  ('20261009010000_provided_syllabus_imports.sql', 'syllabus', 'input_mode'),
  ('20261009010000_provided_syllabus_imports.sql', 'syllabus', 'content_version'),
  ('20261009010000_provided_syllabus_imports.sql', 'syllabus', 'active_import_id'),
  ('20261009010000_provided_syllabus_imports.sql', 'instructional_plans', 'syllabus_content_version'),
  ('20261009010000_provided_syllabus_imports.sql', 'curation', 'syllabus_content_version'),
  ('20261009010000_provided_syllabus_imports.sql', 'materials', 'syllabus_content_version'),
  ('20261009010000_provided_syllabus_imports.sql', 'publication_requests', 'syllabus_content_version'),
  ('20261009090000_fix_voice_audio_processing_compatibility.sql', 'production_jobs', 'audio_processing_attempts')
)
SELECT e.*, EXISTS (SELECT 1 FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public'
  AND c.relname=e.table_name AND a.attname=e.column_name AND a.attnum>0 AND NOT a.attisdropped) AS exists_in_catalog
FROM expected e ORDER BY migration,table_name,column_name;

-- Firmas, SECURITY DEFINER, search_path y definiciones vigentes (incluye wrappers).
-- Algunas funciones fueron trasladadas a private: revisar ambos esquemas.
WITH expected(schema_name, object_name) AS (VALUES
  ('public', 'prevent_ready_sound_effect_binary_mutation'),
  ('public', 'claim_scorm_import_job'),
  ('public', 'heartbeat_scorm_import_job'),
  ('public', 'create_scorm_import_artifact'),
  ('public', 'reset_scorm_material_projection'),
  ('public', 'reconcile_heygen_catalog_snapshot'),
  ('public', 'reconcile_heygen_core_catalog_snapshot'),
  ('public', 'reconcile_heygen_private_catalog_snapshot'),
  ('public', 'set_heygen_catalog_preset_archived'),
  ('public', 'claim_audio_processing_jobs'),
  ('public', 'complete_audio_processing_job'),
  ('public', 'fail_audio_processing_job'),
  ('public', 'claim_audio_processing_jobs_by_profile'),
  ('public', 'record_hyperframes_final_video_checksum'),
  ('public', 'protect_hyperframes_final_video_integrity'),
  ('public', 'enqueue_hyperframes_video_integrity'),
  ('public', 'claim_hyperframes_video_integrity_job'),
  ('public', 'finish_hyperframes_video_integrity_job'),
  ('public', 'record_hyperframes_visual_conformance_evidence'),
  ('public', 'read_hyperframes_visual_conformance_evidence'),
  ('public', 'record_hyperframes_audio_conformance_evidence'),
  ('public', 'read_hyperframes_audio_conformance_evidence'),
  ('public', 'enqueue_hyperframes_full_conformance'),
  ('public', 'claim_hyperframes_conformance_job'),
  ('public', 'renew_hyperframes_conformance_job'),
  ('public', 'finish_hyperframes_conformance_job'),
  ('public', 'read_hyperframes_conformance_report'),
  ('public', 'record_hyperframes_event_visual_conformance_evidence'),
  ('public', 'read_hyperframes_event_visual_conformance_evidence'),
  ('public', 'record_hyperframes_event_batch_measurement'),
  ('public', 'read_hyperframes_event_batch_measurement'),
  ('public', 'verify_hyperframes_event_summary'),
  ('public', 'verify_hyperframes_deck_summary'),
  ('public', 'guard_render_supervisor_key_identity'),
  ('public', 'composition_render_execution_context'),
  ('public', 'issue_composition_render_execution'),
  ('public', 'read_composition_render_execution'),
  ('public', 'consume_composition_render_execution'),
  ('public', 'cancel_composition_render_execution'),
  ('public', 'read_consumed_composition_render_execution'),
  ('public', 'finalize_controlled_composition_render'),
  ('public', 'assert_controlled_render_upload_authority'),
  ('public', 'read_controlled_render_upload'),
  ('public', 'save_controlled_render_upload'),
  ('public', 'check_controlled_render_video_authority'),
  ('public', 'enqueue_controlled_render_worker_job'),
  ('public', 'claim_controlled_render_worker_job'),
  ('public', 'renew_controlled_render_worker_job'),
  ('public', 'finish_controlled_render_worker_job'),
  ('public', 'assert_controlled_render_worker_lease'),
  ('public', 'assert_html_editing_actor'),
  ('public', 'html_editing_grants'),
  ('public', 'register_html_editing_template'),
  ('public', 'read_html_editing_revision'),
  ('public', 'revoke_html_editing_template'),
  ('public', 'append_html_editing_revision'),
  ('public', 'read_html_editing_compilation'),
  ('public', 'read_controlled_render_html_editing_authority'),
  ('public', 'html_snapshot_resource_bindings'),
  ('public', 'commit_html_editing_snapshot'),
  ('public', 'read_html_editing_snapshot_operation'),
  ('public', 'record_html_editing_snapshot_intent'),
  ('public', 'read_html_editing_snapshot_intent'),
  ('public', 'read_narrative_extraction_receipt'),
  ('public', 'commit_narrative_voice_extraction'),
  ('public', 'register_html_editing_template_v2'),
  ('public', 'read_html_editing_bootstrap_context'),
  ('public', 'read_html_editing_restore_revision'),
  ('public', 'commit_html_editing_operation'),
  ('public', 'read_html_editing_operation'),
  ('public', 'commit_html_editing_initialization_operation'),
  ('public', 'read_html_editing_initialization_operation'),
  ('public', 'validate_narrative_fragment_resources'),
  ('public', 'validate_narrative_fragment_caption'),
  ('public', 'validate_narrative_fragment_clip'),
  ('public', 'narrative_fragment_selected_clips'),
  ('public', 'narrative_fragment_document_delta'),
  ('public', 'read_narrative_fragment_receipt'),
  ('public', 'commit_narrative_fragment'),
  ('public', 'record_html_editing_legacy_candidate'),
  ('public', 'read_html_editing_legacy_candidate'),
  ('public', 'revoke_html_editing_legacy_candidate'),
  ('public', 'commit_html_editing_legacy_adoption'),
  ('public', 'read_html_editing_legacy_adoption_operation'),
  ('public', 'record_hyperframes_selected_event_batch_measurement'),
  ('public', 'read_hyperframes_selected_event_batch_measurement'),
  ('public', 'verify_hyperframes_silent_audio_report'),
  ('public', 'register_hyperframes_conformance_render_reservation'),
  ('public', 'read_hyperframes_conformance_render_reservation'),
  ('public', 'attach_hyperframes_conformance_render_outbox'),
  ('public', 'stage_hyperframes_conformance_render_reservation'),
  ('public', 'attach_conformance_outbox_after_job_insert'),
  ('public', 'guard_syllabus_document_quota'),
  ('public', 'guard_syllabus_import_quota'),
  ('public', 'guard_syllabus_import_original'),
  ('public', 'version_syllabus_content'),
  ('public', 'invalidate_syllabus_dependents'),
  ('public', 'transition_syllabus_import'),
  ('public', 'guard_provided_syllabus_fidelity'),
  ('public', 'guard_provided_syllabus_dependency')
)
SELECT n.nspname AS schema_name, p.proname, pg_get_function_identity_arguments(p.oid) AS arguments,
       p.prosecdef AS security_definer, p.proconfig AS configuration,
       has_function_privilege('anon',p.oid,'EXECUTE') AS anon_execute,
       has_function_privilege('authenticated',p.oid,'EXECUTE') AS authenticated_execute,
       has_function_privilege('service_role',p.oid,'EXECUTE') AS service_role_execute,
       pg_get_functiondef(p.oid) AS definition
FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
WHERE n.nspname IN ('public','private') AND p.prokind='f'
  AND (p.proname IN (SELECT object_name FROM expected)
       OR p.proname LIKE 'finish_hyperframes_conformance_job_before_%'
       OR p.proname='append_video_composition_draft_document_v2')
ORDER BY n.nspname,p.proname,arguments;

-- Estructura auxiliar: RLS, triggers, indices y constraints no incluidos en BD.sql.
SELECT n.nspname AS schema_name,c.relname,c.relrowsecurity,c.relforcerowsecurity
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname IN ('public','private') AND c.relkind IN ('r','p') ORDER BY 1,2;
SELECT schemaname,tablename,policyname,roles,cmd,qual,with_check FROM pg_policies
WHERE schemaname IN ('public','private','storage') ORDER BY 1,2,3;
SELECT n.nspname AS schema_name,c.relname,t.tgname,t.tgenabled,pg_get_triggerdef(t.oid) AS definition
FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE NOT t.tgisinternal AND n.nspname IN ('public','private') ORDER BY 1,2,3;
SELECT schemaname,tablename,indexname,indexdef FROM pg_indexes
WHERE schemaname IN ('public','private') ORDER BY 1,2,3;
SELECT n.nspname AS schema_name,c.relname,k.conname,k.convalidated,pg_get_constraintdef(k.oid) AS definition
FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname IN ('public','private') ORDER BY 1,2,3;
SELECT table_schema,table_name,column_name,data_type,is_nullable,column_default FROM information_schema.columns
WHERE table_schema='public' AND (column_name IN ('input_mode','content_version','active_import_id',
  'syllabus_content_version','audio_processing_attempts','audio_processing_lease_token',
  'audio_processing_lease_expires_at','duration_milliseconds')) ORDER BY table_name,column_name;
SELECT id,public,file_size_limit,allowed_mime_types FROM storage.buckets
WHERE id IN ('production-assets','production-render-sources','production-conformance-evidence','organization-fonts') ORDER BY id;
COMMIT;
