export const COMPOSITION_CONFORMANCE_MAX_CHECKPOINTS = 48;
export const COMPOSITION_EVENT_CHECKPOINT_POLICY = "ALL_NATIVE_EVENT_NEIGHBORS_BATCHED_V1" as const;
export const COMPOSITION_CHECKPOINT_PLAN_MAX_REASON_REFERENCES = 131_072;
export const COMPOSITION_CHECKPOINT_UNIFORM_SEGMENTS = 12;
export const COMPOSITION_CHECKPOINT_FRAME_SNAP_EPSILON = 1e-7;
