export const CURATION_CONTENT_VALIDATION_TIMEOUT_MS = 10000;
export const CURATION_MODEL_COOLDOWN_DELAY_MS = 10000;
export const CURATION_REDIRECT_RESOLUTION_TIMEOUT_MS = 8000;
export const MATERIALS_RETRY_BACKOFF_BASE_MS = 15000;
