import crypto from "crypto";
import JSZip from "jszip";
import type { BundleAgentSpec } from "./types";
import { buildBundleBlueprint } from "./blueprint.service";
import { buildBundleManifest } from "./manifest.service";
import { buildBundleTemplateSource } from "./template-source.service";

function buildPackageJson() {
  return {
    private: true,
    dependencies: {
      react: "19.2.3",
      "react-dom": "19.2.3",
      remotion: "4.0.484",
    },
  };
}

function buildReadme(spec: BundleAgentSpec) {
  const blueprint = buildBundleBlueprint(spec);

  return `# ${spec.title}

Generated by SofLIA Bundle Agent as a non-approved draft bundle.

## Contract

- Source ZIP: yes
- Remotion export mode: root
- Composition ID: ${blueprint.compositionId}
- Layout blueprint: ${blueprint.layout}
- Timeline blueprint: ${blueprint.timeline}
- Text rendering: ${blueprint.renderText ? "enabled" : "disabled"}

## Editable Layers

Editable layer metadata is declared in courseforge-remotion-template.json. The layout editor uses those default boxes before saving user changes as layoutOverrides.
`;
}

function buildManifest(spec: BundleAgentSpec) {
  const blueprint = buildBundleBlueprint(spec);
  return buildBundleManifest(spec, blueprint);
}

function buildTemplateSource(spec: BundleAgentSpec) {
  const blueprint = buildBundleBlueprint(spec);
  return buildBundleTemplateSource(blueprint);
}

export function buildBaseBundleSpec(): BundleAgentSpec {
  return {
    title: "SofLIA - Engine Remotion Template Base",
    description: "Base segura para crear un bundle Remotion externo compatible con SofLIA - Engine.",
    visualStyle: "estructura base con avatar, contenido lateral, slides, B-roll y capas editables",
    compositionId: "courseforge-template-base",
    durationFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    requiredAssets: ["audio", "slides", "avatar", "broll"],
    propsSchema: {
      type: "object",
      properties: {
        accentColor: { type: "string", description: "Color de acento opcional." },
      },
    },
    defaultProps: {
      accentColor: "#00D4B3",
    },
    changeSummary: "Base externa descargable para autores de bundles Remotion.",
  };
}

export async function buildControlledBundleZip(spec: BundleAgentSpec): Promise<{
  buffer: ArrayBuffer;
  hash: string;
  originalFileName: string;
}> {
  const zip = new JSZip();
  zip.file("courseforge-remotion-template.json", JSON.stringify(buildManifest(spec), null, 2));
  zip.file("src/index.tsx", buildTemplateSource(spec));
  zip.file("package.json", JSON.stringify(buildPackageJson(), null, 2));
  zip.file("README.md", buildReadme(spec));

  const buffer = await zip.generateAsync({ type: "arraybuffer", compression: "DEFLATE" });
  const hash = crypto.createHash("sha256").update(Buffer.from(buffer)).digest("hex");

  return {
    buffer,
    hash,
    originalFileName: `${spec.compositionId}.zip`,
  };
}

export async function buildExternalAuthorBundleBaseZip(): Promise<{
  buffer: ArrayBuffer;
  hash: string;
  originalFileName: string;
}> {
  const spec = buildBaseBundleSpec();
  const bundle = await buildControlledBundleZip(spec);

  return {
    ...bundle,
    originalFileName: "courseforge-remotion-template-base.zip",
  };
}
