import crypto from "crypto";
import JSZip from "jszip";
import { DEFAULT_BUNDLE_AGENT_CREATIVE_BRIEF, bundleAgentSpecSchema, type BundleAgentSpec } from "./types";
import { buildBundleBlueprint } from "./blueprint.service";
import { buildBundleManifest } from "./manifest.service";
import { buildBundleTemplateSource } from "./template-source.service";

function buildPackageJson() {
  return {
    private: true,
    dependencies: {
      react: "19.2.3",
      "react-dom": "19.2.3",
      remotion: "4.0.484",
    },
  };
}

function buildReadme(spec: BundleAgentSpec) {
  const blueprint = buildBundleBlueprint(spec);
  const creativeBrief = spec.creativeBrief;
  const editableLayerLines = blueprint.editableLayers
    .map((layer) => {
      const box = layer.defaultBox;
      const pattern = layer.itemLayerIdPattern ? `, items: ${layer.itemLayerIdPattern}` : "";
      return `- ${layer.layerId}: x ${box?.x}, y ${box?.y}, width ${box?.width}, height ${box?.height}, stack ${layer.defaultStackOrder ?? 0}${pattern}`;
    })
    .join("\n");
  const visualVariantLines = creativeBrief.visualVariants
    .map((variant) => `- ${variant.id}: ${variant.name} - ${variant.composition}`)
    .join("\n");

  return `# ${spec.title}

Generated by SofLIA Bundle Agent as a non-approved draft bundle.

## Contract

- Source ZIP: yes
- Render export mode: root
- Layout contract: v2
- Coordinate space: canvas pixels
- Composition ID: ${blueprint.compositionId}
- Layout blueprint: ${blueprint.layout}
- Timeline blueprint: ${blueprint.timeline}
- Text rendering: ${blueprint.renderText ? "enabled" : "disabled"}

## Creative Direction

- Direction: ${creativeBrief.directionName}
- Layout system: ${creativeBrief.layoutSystem}
- Motion language: ${creativeBrief.motionLanguage}
- Palette: ${creativeBrief.colorTokens.paletteName} (${creativeBrief.colorTokens.accent})

## Visual Variants

${visualVariantLines}

## Editable Layers

Editable layer metadata is declared in the template manifest. Every defaultBox and layout override uses global canvas coordinates. Editable layers must be rendered directly below AbsoluteFill so nested containers cannot change the x/y origin.

${editableLayerLines}

Slide and B-roll item patterns are expanded at runtime from the assets received by the composition. Item overrides are applied after their group override, while stack changes remain scoped to the declared group layers.
`;
}

function buildManifest(spec: BundleAgentSpec) {
  const blueprint = buildBundleBlueprint(spec);
  return buildBundleManifest(spec, blueprint);
}

function buildTemplateSource(spec: BundleAgentSpec) {
  const blueprint = buildBundleBlueprint(spec);
  return buildBundleTemplateSource(blueprint);
}

export function buildBaseBundleSpec(): BundleAgentSpec {
  return {
    title: "SofLIA - Engine Video Template Base",
    description: "Base segura para crear un bundle externo compatible con SofLIA - Engine.",
    visualStyle: "estructura base con avatar, contenido lateral, slides, B-roll y capas editables",
    creativeBrief: DEFAULT_BUNDLE_AGENT_CREATIVE_BRIEF,
    compositionId: "soflia-engine-template-base",
    durationFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    requiredAssets: ["audio", "slides", "avatar", "broll"],
    propsSchema: {
      type: "object",
      properties: {
        accentColor: { type: "string", description: "Color de acento opcional." },
      },
    },
    defaultProps: {
      accentColor: "#00D4B3",
    },
    changeSummary: "Base externa descargable para autores de bundles de video.",
  };
}

export async function buildControlledBundleZip(spec: BundleAgentSpec): Promise<{
  buffer: ArrayBuffer;
  hash: string;
  originalFileName: string;
}> {
  const normalizedSpec = bundleAgentSpecSchema.parse(spec);
  const zip = new JSZip();
  zip.file("courseforge-remotion-template.json", JSON.stringify(buildManifest(normalizedSpec), null, 2));
  zip.file("src/index.tsx", buildTemplateSource(normalizedSpec));
  zip.file("package.json", JSON.stringify(buildPackageJson(), null, 2));
  zip.file("README.md", buildReadme(normalizedSpec));

  const buffer = await zip.generateAsync({ type: "arraybuffer", compression: "DEFLATE" });
  const hash = crypto.createHash("sha256").update(Buffer.from(buffer)).digest("hex");

  return {
    buffer,
    hash,
    originalFileName: `${normalizedSpec.compositionId}.zip`,
  };
}

export async function buildExternalAuthorBundleBaseZip(): Promise<{
  buffer: ArrayBuffer;
  hash: string;
  originalFileName: string;
}> {
  const spec = buildBaseBundleSpec();
  const bundle = await buildControlledBundleZip(spec);

  return {
    ...bundle,
    originalFileName: "soflia-engine-video-template-base.zip",
  };
}
