import crypto from "crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import JSZip from "jszip";
import { z } from "zod";
import skillManifest from "@/domains/production/slides/templates/soflia-deck/soflia-deck.skill-manifest.json";
import templateManifest from "@/domains/production/slides/templates/soflia-deck/soflia-deck.template-manifest.json";
import exampleDeck from "@/domains/production/slides/templates/soflia-deck/examples/soflia-course-lesson.deck.json";

const slideTemplateSpecSchema = z.object({
  artifactKind: z.literal("slide_template"),
  changeSummary: z.string().trim().max(1000),
  description: z.string().trim().max(1000),
  examples: z.array(z.record(z.string(), z.unknown())).min(1).max(8),
  packageId: z.string().trim().min(1).max(120),
  skillManifest: z.record(z.string(), z.unknown()),
  templateManifest: z.record(z.string(), z.unknown()),
  title: z.string().trim().min(1).max(120),
});

export type SlideTemplateAgentSpec = z.infer<typeof slideTemplateSpecSchema>;

function slugifyPackageId(value: string) {
  const normalized = value
    .normalize("NFKD")
    .replace(/[^\w\s.-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/_+/g, "-")
    .toLowerCase()
    .slice(0, 90);

  return /^[a-z0-9]/.test(normalized) ? normalized : "soflia-deck-template";
}

function latestUserText(messages: Array<{ role: string; content_redacted: string }>) {
  return [...messages]
    .reverse()
    .find((message) => message.role === "USER")
    ?.content_redacted
    .trim() || "";
}

function inferSlideTemplateTitle(input: {
  fallbackTitle?: string | null;
  messages: Array<{ role: string; content_redacted: string }>;
}) {
  const fallback = input.fallbackTitle?.trim();
  const latest = latestUserText(input.messages);
  if (fallback && !/^nuevo bundle de video$/i.test(fallback)) {
    return fallback.slice(0, 120);
  }

  const firstSentence = latest
    .split(/[.\n]/)
    .map((part) => part.trim())
    .find(Boolean);

  return (firstSentence || "Plantilla SofLIA Deck").slice(0, 120);
}

function inferDescription(messages: Array<{ role: string; content_redacted: string }>, title: string) {
  const userText = messages
    .filter((message) => message.role === "USER")
    .map((message) => message.content_redacted)
    .join("\n")
    .replace(/\s+/g, " ")
    .trim();

  return (userText || `Plantilla de slides ${title} para SofLIA - Engine.`).slice(0, 1000);
}

function templateAssetPath(fileName: string) {
  return [
    path.join(process.cwd(), "src", "domains", "production", "slides", "templates", "soflia-deck", fileName),
    path.join(process.cwd(), "apps", "web", "src", "domains", "production", "slides", "templates", "soflia-deck", fileName),
  ];
}

async function readTemplateAsset(fileName: string) {
  const errors: string[] = [];
  for (const candidate of templateAssetPath(fileName)) {
    try {
      return await readFile(candidate, "utf8");
    } catch (error) {
      errors.push(error instanceof Error ? error.message : String(error));
    }
  }

  throw new Error(`No se pudo leer ${fileName}: ${errors.join(" | ")}`);
}

export function buildSlideTemplateSpecFromConversation(input: {
  title?: string | null;
  messages: Array<{ role: string; content_redacted: string }>;
  overrides?: unknown;
}): SlideTemplateAgentSpec {
  const title = inferSlideTemplateTitle({
    fallbackTitle: input.title,
    messages: input.messages,
  });
  const description = inferDescription(input.messages, title);
  const packageId = slugifyPackageId(title);
  const changeSummary = input.messages.filter((message) => message.role === "USER").length > 1
    ? `SofLIA adjusted the slide template package using the latest feedback: ${latestUserText(input.messages).slice(0, 220)}`
    : "SofLIA generated a SofLIA Deck slide-template package from the conversation.";

  return slideTemplateSpecSchema.parse({
    artifactKind: "slide_template",
    changeSummary,
    description,
    examples: [exampleDeck],
    packageId,
    skillManifest,
    templateManifest,
    title,
    ...(input.overrides && typeof input.overrides === "object" ? input.overrides : {}),
  });
}

function buildReadme(spec: SlideTemplateAgentSpec) {
  return `# ${spec.title}

Generated by SofLIA - Engine as a slide-template package.

## Contract

- Artifact kind: slide_template
- Skill: ${String(spec.skillManifest.id || "soflia-deck")}
- Template: ${String(spec.templateManifest.id || "soflia-deck-template")}
- Runtime: self-contained HTML deck
- Canvas: 1920x1080
- Charts: declarative JSON rendered as responsive inline SVG

## Files

- skill/soflia-deck.skill.md
- manifests/soflia-deck.skill-manifest.json
- manifests/soflia-deck.template-manifest.json
- runtime/example.html
- schemas/soflia-deck.input-schema.json
- examples/soflia-course-lesson.deck.json

This package is not a Remotion bundle and must not be registered as a Remotion template version.
`;
}

export async function buildSlideTemplatePackageZip(spec: SlideTemplateAgentSpec): Promise<{
  buffer: ArrayBuffer;
  hash: string;
  originalFileName: string;
  validationReport: {
    isValid: boolean;
    errors: string[];
    warnings: string[];
    info: Record<string, unknown>;
  };
}> {
  const normalizedSpec = slideTemplateSpecSchema.parse(spec);
  const zip = new JSZip();
  const skillMarkdown = await readTemplateAsset("soflia-deck.skill.md");
  const exampleHtml = await readTemplateAsset("example.html");

  zip.file("skill/soflia-deck.skill.md", skillMarkdown);
  zip.file("runtime/example.html", exampleHtml);
  zip.file("manifests/soflia-deck.skill-manifest.json", JSON.stringify(normalizedSpec.skillManifest, null, 2));
  zip.file("manifests/soflia-deck.template-manifest.json", JSON.stringify(normalizedSpec.templateManifest, null, 2));
  zip.file("schemas/soflia-deck.input-schema.json", JSON.stringify(normalizedSpec.templateManifest.inputSchema, null, 2));
  zip.file("examples/soflia-course-lesson.deck.json", JSON.stringify(normalizedSpec.examples[0], null, 2));
  zip.file("package-spec.json", JSON.stringify(normalizedSpec, null, 2));
  zip.file("README.md", buildReadme(normalizedSpec));

  const buffer = await zip.generateAsync({ type: "arraybuffer", compression: "DEFLATE" });
  const hash = crypto.createHash("sha256").update(Buffer.from(buffer)).digest("hex");

  return {
    buffer,
    hash,
    originalFileName: `${normalizedSpec.packageId}.slide-template.zip`,
    validationReport: {
      errors: [],
      info: {
        artifactKind: "slide_template",
        exampleCount: normalizedSpec.examples.length,
        hash,
        skillId: normalizedSpec.skillManifest.id,
        templateId: normalizedSpec.templateManifest.id,
      },
      isValid: true,
      warnings: [],
    },
  };
}

export function parseSlideTemplateAgentSpec(value: unknown) {
  return slideTemplateSpecSchema.parse(value);
}
