import crypto from "crypto";
import { bundleAgentSpecSchema, type BundleAgentSpec } from "./types";

function slugifyCompositionId(value: string) {
  const normalized = value
    .normalize("NFKD")
    .replace(/[^\w\s.:-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/_+/g, "-")
    .slice(0, 72);

  return /^[A-Za-z0-9]/.test(normalized) ? normalized : "soflia-template";
}

export function stableJsonHash(value: unknown): string {
  return crypto.createHash("sha256").update(stableStringify(value)).digest("hex");
}

export function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }

  if (Array.isArray(value)) {
    return `[${value.map(stableStringify).join(",")}]`;
  }

  const record = value as Record<string, unknown>;
  return `{${Object.keys(record)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${stableStringify(record[key])}`)
    .join(",")}}`;
}

export function buildSpecFromConversation(input: {
  title?: string | null;
  messages: Array<{ role: string; content_redacted: string }>;
  overrides?: unknown;
}): BundleAgentSpec {
  const userText = input.messages
    .filter((message) => message.role === "USER")
    .map((message) => message.content_redacted)
    .join("\n")
    .trim();
  const title = (input.title || userText.split(/\n|\.|,/)[0] || "SofLIA Remotion bundle").slice(0, 120);
  const inferredStyle = userText.slice(0, 220) || "Clean educational motion graphics with readable text and soft transitions.";

  return bundleAgentSpecSchema.parse({
    title,
    description: userText.slice(0, 1000),
    visualStyle: inferredStyle,
    compositionId: slugifyCompositionId(title),
    durationFrames: 150,
    fps: 30,
    width: 1920,
    height: 1080,
    requiredAssets: ["slides", "audio"],
    defaultProps: {
      title,
      subtitle: "Generated by SofLIA Bundle Agent",
    },
    propsSchema: {
      type: "object",
      properties: {
        title: { type: "string", description: "Main title displayed in the composition" },
        subtitle: { type: "string", description: "Secondary text displayed in the composition" },
      },
    },
    changeSummary: "SofLIA generated a controlled Remotion bundle draft from the conversation.",
    ...(input.overrides && typeof input.overrides === "object" ? input.overrides : {}),
  });
}

export function computeSpecHash(spec: BundleAgentSpec): string {
  return stableJsonHash(spec);
}
