-- Migración DEFINITIVA para model_settings
BEGIN;

-- 1. Forzar limpieza de identidad previa
-- DROP IDENTITY IF EXISTS es la forma estándar de hacerlo en Postgres 10+
ALTER TABLE public.model_settings ALTER COLUMN id DROP IDENTITY IF EXISTS;

-- 2. Limpiar cualquier default residual
ALTER TABLE public.model_settings ALTER COLUMN id DROP DEFAULT;

-- 3. Agregar la propiedad IDENTITY limpia
ALTER TABLE public.model_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 4. Sincronizar la secuencia con los IDs existentes
SELECT setval(
    pg_get_serial_sequence('public.model_settings', 'id'), 
    coalesce(max(id), 1),
    max(id) IS NOT NULL
) FROM public.model_settings;

COMMIT;
