-- ============================================================================
-- Migration: Materialized previews for custom Remotion template builds
-- Date: 2026-07-20
-- Description:
--   Stores auditable poster/video previews generated by desktop workers for a
--   specific custom template build + component props hash. Build artifacts and
--   preview artifacts are intentionally separated: builds are reusable compiled
--   bundles, previews are component/layout-specific visual snapshots.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.remotion_template_previews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL
    REFERENCES public.organizations(id) ON DELETE CASCADE,
  template_id uuid NOT NULL
    REFERENCES public.remotion_templates(id) ON DELETE CASCADE,
  template_version_id uuid NOT NULL
    REFERENCES public.remotion_template_versions(id) ON DELETE CASCADE,
  template_build_id uuid NOT NULL
    REFERENCES public.remotion_template_builds(id) ON DELETE CASCADE,
  material_component_id uuid
    REFERENCES public.material_components(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'QUEUED',
  props_hash text NOT NULL,
  layout_overrides_hash text,
  resolved_props jsonb NOT NULL DEFAULT '{}'::jsonb,
  composition_id text NOT NULL,
  bundle_hash text,
  build_hash text,
  preview_frame integer NOT NULL DEFAULT 0,
  preview_poster_storage_path text,
  preview_video_storage_path text,
  preview_duration_seconds integer,
  preview_frames integer,
  worker_id uuid REFERENCES public.render_workers(id) ON DELETE SET NULL,
  claimed_at timestamp with time zone,
  worker_heartbeat_at timestamp with time zone,
  lease_expires_at timestamp with time zone,
  provider_status text,
  provider_status_detail text,
  progress jsonb NOT NULL DEFAULT '[]'::jsonb,
  output_checksum text,
  error_code text,
  error_message text,
  requested_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  CONSTRAINT remotion_template_previews_pkey PRIMARY KEY (id),
  CONSTRAINT remotion_template_previews_status_check CHECK (
    status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')
  )
);

CREATE INDEX IF NOT EXISTS idx_remotion_template_previews_lookup
  ON public.remotion_template_previews (
    template_build_id,
    material_component_id,
    props_hash,
    layout_overrides_hash,
    created_at DESC
  );

CREATE INDEX IF NOT EXISTS idx_remotion_template_previews_worker_claim
  ON public.remotion_template_previews (
    organization_id,
    status,
    lease_expires_at,
    created_at
  )
  WHERE status IN ('QUEUED', 'RUNNING');

CREATE INDEX IF NOT EXISTS idx_remotion_template_previews_worker_id
  ON public.remotion_template_previews (worker_id)
  WHERE worker_id IS NOT NULL;

ALTER TABLE public.remotion_template_previews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "select_remotion_template_previews"
  ON public.remotion_template_previews
  FOR SELECT
  USING (organization_id::text = public.get_active_org_id());

CREATE POLICY "insert_remotion_template_previews"
  ON public.remotion_template_previews
  FOR INSERT
  WITH CHECK (organization_id::text = public.get_active_org_id());

CREATE POLICY "update_remotion_template_previews"
  ON public.remotion_template_previews
  FOR UPDATE
  USING (organization_id::text = public.get_active_org_id())
  WITH CHECK (organization_id::text = public.get_active_org_id());

COMMENT ON TABLE public.remotion_template_previews IS
  'Materialized preview artifacts for custom Remotion templates generated by desktop workers.';

COMMENT ON COLUMN public.remotion_template_previews.props_hash IS
  'Stable hash of resolved Remotion input props used for this preview.';

COMMENT ON COLUMN public.remotion_template_previews.layout_overrides_hash IS
  'Stable hash of layoutOverrides included in props, used to detect stale visual previews.';

COMMENT ON COLUMN public.remotion_template_previews.preview_poster_storage_path IS
  'Durable storage path for the generated preview poster image.';

COMMENT ON COLUMN public.remotion_template_previews.preview_video_storage_path IS
  'Optional durable storage path for a short MP4 preview.';
