-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  username text UNIQUE,
  email text,
  first_name text,
  last_name_father text,
  last_name_mother text,
  avatar_url text,
  platform_role USER-DEFINED NOT NULL DEFAULT 'CONSTRUCTOR'::app_role,
  organization_id uuid,
  organization_role text,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.login_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  login_at timestamp with time zone DEFAULT now(),
  ip_address text,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT login_history_pkey PRIMARY KEY (id),
  CONSTRAINT login_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  token_hash text NOT NULL,
  device_info text,
  ip_address text,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.artifacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id text,
  course_id text,
  idea_central text NOT NULL,
  nombres jsonb NOT NULL DEFAULT '[]'::jsonb,
  objetivos jsonb NOT NULL DEFAULT '[]'::jsonb,
  descripcion jsonb NOT NULL DEFAULT '{}'::jsonb,
  state USER-DEFINED NOT NULL DEFAULT 'DRAFT'::artifact_state,
  validation_report jsonb,
  semantic_result jsonb,
  auto_retry_count integer NOT NULL DEFAULT 0,
  iteration_count integer NOT NULL DEFAULT 0,
  generation_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  production_complete boolean DEFAULT false,
  organization_id uuid,
  CONSTRAINT artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT artifacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.syllabus (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  route text NOT NULL DEFAULT 'B_NO_SOURCE'::text CHECK (route = ANY (ARRAY['A_WITH_SOURCE'::text, 'B_NO_SOURCE'::text])),
  modules jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_summary jsonb,
  validation jsonb NOT NULL DEFAULT '{"checks": [], "automatic_pass": false}'::jsonb,
  qa jsonb NOT NULL DEFAULT '{"status": "PENDING"}'::jsonb,
  state text NOT NULL DEFAULT 'STEP_DRAFT'::text,
  iteration_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT syllabus_pkey PRIMARY KEY (id),
  CONSTRAINT syllabus_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.instructional_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  lesson_plans jsonb NOT NULL DEFAULT '[]'::jsonb,
  blockers jsonb NOT NULL DEFAULT '[]'::jsonb,
  dod jsonb NOT NULL DEFAULT '{"checklist": [], "semantic_checks": [], "automatic_checks": []}'::jsonb,
  approvals jsonb NOT NULL DEFAULT '{"architect_status": "PENDING"}'::jsonb,
  final_status text,
  state text NOT NULL DEFAULT 'STEP_DRAFT'::text,
  iteration_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  validation jsonb,
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT instructional_plans_pkey PRIMARY KEY (id),
  CONSTRAINT instructional_plans_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.system_prompts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  version text NOT NULL DEFAULT '1.0.0'::text,
  content text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT system_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT system_prompts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.curation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  attempt_number integer NOT NULL DEFAULT 1 CHECK (attempt_number = ANY (ARRAY[1, 2])),
  state text NOT NULL DEFAULT 'PHASE2_DRAFT'::text,
  qa_decision jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT curation_pkey PRIMARY KEY (id),
  CONSTRAINT curation_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.curation_rows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  curation_id uuid NOT NULL,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  component text NOT NULL,
  is_critical boolean NOT NULL DEFAULT false,
  source_ref text NOT NULL,
  source_title text,
  source_rationale text,
  url_status text NOT NULL DEFAULT 'PENDING'::text,
  http_status_code integer,
  last_checked_at timestamp with time zone,
  failure_reason text,
  apta boolean,
  motivo_no_apta text,
  cobertura_completa boolean,
  notes text,
  auto_evaluated boolean DEFAULT false,
  auto_reason text,
  forbidden_override boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT curation_rows_pkey PRIMARY KEY (id),
  CONSTRAINT curation_rows_curation_id_fkey FOREIGN KEY (curation_id) REFERENCES public.curation(id)
);
CREATE TABLE public.curation_blockers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  curation_id uuid NOT NULL,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  component text NOT NULL,
  impact text NOT NULL,
  owner text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN'::text CHECK (status = ANY (ARRAY['OPEN'::text, 'MITIGATING'::text, 'ACCEPTED'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT curation_blockers_pkey PRIMARY KEY (id),
  CONSTRAINT curation_blockers_curation_id_fkey FOREIGN KEY (curation_id) REFERENCES public.curation(id)
);
CREATE TABLE public.model_settings (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  model_name text NOT NULL DEFAULT 'gemini-2.5-flash'::text,
  temperature numeric NOT NULL DEFAULT 0.70,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  fallback_model text NOT NULL DEFAULT 'gemini-2.5-flash'::text,
  thinking_level text NOT NULL DEFAULT 'medium'::text CHECK (thinking_level = ANY (ARRAY['minimal'::text, 'low'::text, 'medium'::text, 'high'::text])),
  setting_type text DEFAULT 'SEARCH'::text CHECK (setting_type = ANY (ARRAY['ARTIFACT_BASE'::text, 'SYLLABUS'::text, 'INSTRUCTIONAL_PLAN'::text, 'MATERIALS'::text, 'CURATION'::text])),
  organization_id uuid,
  CONSTRAINT model_settings_pkey PRIMARY KEY (id),
  CONSTRAINT model_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  version integer NOT NULL DEFAULT 1,
  prompt_version text NOT NULL DEFAULT 'default'::text,
  state text NOT NULL DEFAULT 'PHASE3_DRAFT'::text,
  qa_decision jsonb,
  package jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lessons jsonb DEFAULT '[]'::jsonb,
  global_blockers jsonb DEFAULT '[]'::jsonb,
  dod jsonb DEFAULT '{"checklist": [], "automatic_checks": []}'::jsonb,
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT materials_pkey PRIMARY KEY (id),
  CONSTRAINT materials_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.material_lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  materials_id uuid NOT NULL,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  module_id text NOT NULL,
  module_title text NOT NULL,
  oa_text text NOT NULL,
  expected_components ARRAY NOT NULL DEFAULT '{}'::text[],
  quiz_spec jsonb,
  requires_demo_guide boolean DEFAULT false,
  dod jsonb NOT NULL DEFAULT '{}'::jsonb,
  state text NOT NULL DEFAULT 'PENDING'::text,
  iteration_count integer NOT NULL DEFAULT 0,
  max_iterations integer NOT NULL DEFAULT 5,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT material_lessons_pkey PRIMARY KEY (id),
  CONSTRAINT material_lessons_materials_id_fkey FOREIGN KEY (materials_id) REFERENCES public.materials(id)
);
CREATE TABLE public.material_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_lesson_id uuid NOT NULL,
  type text NOT NULL,
  content jsonb NOT NULL,
  source_refs ARRAY DEFAULT '{}'::text[],
  validation_status text NOT NULL DEFAULT 'PENDING'::text,
  validation_errors ARRAY DEFAULT '{}'::text[],
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  iteration_number integer NOT NULL DEFAULT 1,
  assets jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT material_components_pkey PRIMARY KEY (id),
  CONSTRAINT material_components_material_lesson_id_fkey FOREIGN KEY (material_lesson_id) REFERENCES public.material_lessons(id)
);
CREATE TABLE public.publication_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  category text NOT NULL,
  level text NOT NULL CHECK (level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  instructor_email text NOT NULL,
  thumbnail_url text,
  slug text NOT NULL,
  price numeric DEFAULT 0.00,
  lesson_videos jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'DRAFT'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'READY'::text, 'SENT'::text, 'APPROVED'::text, 'REJECTED'::text])),
  soflia_course_id uuid,
  soflia_response jsonb,
  sent_at timestamp with time zone,
  response_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  selected_lessons jsonb,
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT publication_requests_pkey PRIMARY KEY (id),
  CONSTRAINT publication_requests_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.scorm_imports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid,
  original_filename text NOT NULL,
  storage_path text NOT NULL,
  scorm_version text,
  manifest_raw jsonb,
  organizations jsonb,
  resources jsonb,
  sco_count integer DEFAULT 0,
  status text DEFAULT 'UPLOADED'::text,
  processing_step text,
  error_message text,
  content_analysis jsonb DEFAULT '{}'::jsonb,
  detected_components jsonb DEFAULT '[]'::jsonb,
  gaps_detected jsonb DEFAULT '[]'::jsonb,
  enrichment_plan jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_by uuid,
  organization_id uuid,
  CONSTRAINT scorm_imports_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_imports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT scorm_imports_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT scorm_imports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.scorm_resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scorm_import_id uuid,
  resource_identifier text NOT NULL,
  scorm_type text,
  href text,
  files jsonb DEFAULT '[]'::jsonb,
  extracted_path text,
  content_type text,
  raw_html text,
  clean_text text,
  word_count integer DEFAULT 0,
  images jsonb DEFAULT '[]'::jsonb,
  videos jsonb DEFAULT '[]'::jsonb,
  documents jsonb DEFAULT '[]'::jsonb,
  has_quiz boolean DEFAULT false,
  quiz_raw jsonb,
  quiz_transformed jsonb,
  mapped_to_lesson_id text,
  material_component_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scorm_resources_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_resources_scorm_import_id_fkey FOREIGN KEY (scorm_import_id) REFERENCES public.scorm_imports(id)
);
CREATE TABLE public.pipeline_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL,
  event_type text NOT NULL,
  event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  step_id text,
  entity_id text,
  entity_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pipeline_events_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_events_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.production_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  artifact_id uuid NOT NULL,
  material_lesson_id uuid,
  material_component_id uuid,
  lesson_id text,
  module_id text,
  job_type text NOT NULL,
  provider text NOT NULL,
  provider_model text,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'QUEUED'::text, 'RUNNING'::text, 'WAITING_PROVIDER'::text, 'SUCCEEDED'::text, 'FAILED'::text, 'CANCELLED'::text, 'RETRY_SCHEDULED'::text])),
  idempotency_key text NOT NULL,
  attempt integer NOT NULL DEFAULT 1,
  input_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  progress jsonb NOT NULL DEFAULT '[]'::jsonb,
  provider_request_id text,
  provider_job_id text,
  provider_callback_id text,
  provider_error jsonb,
  estimated_cost_cents integer,
  actual_cost_cents integer,
  duration_seconds integer,
  created_by uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT production_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT production_jobs_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT production_jobs_material_lesson_id_fkey FOREIGN KEY (material_lesson_id) REFERENCES public.material_lessons(id),
  CONSTRAINT production_jobs_material_component_id_fkey FOREIGN KEY (material_component_id) REFERENCES public.material_components(id),
  CONSTRAINT production_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.production_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  artifact_id uuid NOT NULL,
  production_job_id uuid,
  material_lesson_id uuid,
  material_component_id uuid,
  lesson_id text,
  module_id text,
  asset_type text NOT NULL,
  provider text,
  storage_bucket text,
  storage_path text,
  public_url text,
  external_url text,
  mime_type text,
  file_size_bytes bigint,
  duration_seconds integer,
  checksum text,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  qa_status text NOT NULL DEFAULT 'PENDING'::text CHECK (qa_status = ANY (ARRAY['PENDING'::text, 'GENERATED'::text, 'READY_FOR_QA'::text, 'APPROVED'::text, 'REJECTED'::text, 'EXPORTED'::text, 'PUBLISHED'::text, 'ARCHIVED'::text])),
  qa_notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT production_assets_pkey PRIMARY KEY (id),
  CONSTRAINT production_assets_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT production_assets_production_job_id_fkey FOREIGN KEY (production_job_id) REFERENCES public.production_jobs(id),
  CONSTRAINT production_assets_material_lesson_id_fkey FOREIGN KEY (material_lesson_id) REFERENCES public.material_lessons(id),
  CONSTRAINT production_assets_material_component_id_fkey FOREIGN KEY (material_component_id) REFERENCES public.material_components(id),
  CONSTRAINT production_assets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.remotion_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  description text,
  entry_point text NOT NULL DEFAULT 'index.tsx'::text,
  config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_public boolean NOT NULL DEFAULT false,
  storage_path text,
  thumbnail_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  bundle_status text NOT NULL DEFAULT 'NOT_APPLICABLE'::text CHECK (bundle_status = ANY (ARRAY['NOT_APPLICABLE'::text, 'VALIDATING'::text, 'STORED_REFERENCE'::text, 'PENDING_REVIEW'::text, 'APPROVED'::text, 'APPROVED_FOR_SANDBOX'::text, 'SANDBOX_VALIDATION_FAILED'::text, 'REJECTED'::text])),
  composition_id text,
  CONSTRAINT remotion_templates_pkey PRIMARY KEY (id),
  CONSTRAINT remotion_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_acquired_templates (
  organization_id uuid NOT NULL,
  template_id uuid NOT NULL,
  acquired_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_acquired_templates_pkey PRIMARY KEY (organization_id, template_id),
  CONSTRAINT organization_acquired_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_acquired_templates_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id)
);
CREATE TABLE public.user_cloud_storage_credentials (
  user_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['google_drive'::text, 'onedrive'::text])),
  account_email text NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  scopes ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  CONSTRAINT user_cloud_storage_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT user_cloud_storage_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_cloud_storage_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.remotion_template_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  version_number integer NOT NULL,
  status text NOT NULL DEFAULT 'UPLOADED'::text CHECK (status = ANY (ARRAY['UPLOADED'::text, 'VALIDATING'::text, 'VALIDATION_FAILED'::text, 'PENDING_REVIEW'::text, 'APPROVED'::text, 'APPROVED_FOR_SANDBOX'::text, 'SANDBOX_VALIDATION_FAILED'::text, 'REJECTED'::text, 'DEPRECATED'::text])),
  storage_path text NOT NULL,
  original_file_name text,
  bundle_hash text,
  entry_point text,
  manifest jsonb,
  validation_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  validated_at timestamp with time zone,
  approved_at timestamp with time zone,
  approved_by uuid,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  rejection_reason text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  template_type text NOT NULL DEFAULT 'custom_bundle'::text CHECK (template_type = ANY (ARRAY['simple'::text, 'custom_bundle'::text])),
  export_mode text NOT NULL DEFAULT 'component'::text CHECK (export_mode = ANY (ARRAY['component'::text, 'root'::text])),
  composition_id text,
  composition_ids jsonb,
  props_schema jsonb,
  default_props jsonb,
  default_duration_frames integer,
  default_fps integer,
  default_width integer,
  default_height integer,
  build_status text NOT NULL DEFAULT 'PENDING'::text CHECK (build_status = ANY (ARRAY['PENDING'::text, 'BUILDING'::text, 'BUILT'::text, 'BUILD_FAILED'::text])),
  build_hash text,
  build_output_path text,
  built_at timestamp with time zone,
  CONSTRAINT remotion_template_versions_pkey PRIMARY KEY (id),
  CONSTRAINT remotion_template_versions_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id),
  CONSTRAINT remotion_template_versions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT remotion_template_versions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT remotion_template_versions_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.profiles(id),
  CONSTRAINT remotion_template_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  platform_role USER-DEFINED NOT NULL DEFAULT 'CONSTRUCTOR'::app_role,
  source text NOT NULL DEFAULT 'courseforge'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT organization_user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);