-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  username text UNIQUE,
  email text,
  first_name text,
  last_name_father text,
  last_name_mother text,
  avatar_url text,
  platform_role USER-DEFINED NOT NULL DEFAULT 'CONSTRUCTOR'::app_role,
  organization_id uuid,
  organization_role text,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.login_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  login_at timestamp with time zone DEFAULT now(),
  ip_address text,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT login_history_pkey PRIMARY KEY (id),
  CONSTRAINT login_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  token_hash text NOT NULL,
  device_info text,
  ip_address text,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.artifacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id text,
  course_id text,
  idea_central text NOT NULL,
  nombres jsonb NOT NULL DEFAULT '[]'::jsonb,
  objetivos jsonb NOT NULL DEFAULT '[]'::jsonb,
  descripcion jsonb NOT NULL DEFAULT '{}'::jsonb,
  state USER-DEFINED NOT NULL DEFAULT 'DRAFT'::artifact_state,
  validation_report jsonb,
  semantic_result jsonb,
  auto_retry_count integer NOT NULL DEFAULT 0,
  iteration_count integer NOT NULL DEFAULT 0,
  generation_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  production_complete boolean DEFAULT false,
  organization_id uuid,
  CONSTRAINT artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT artifacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.syllabus (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  route text NOT NULL DEFAULT 'B_NO_SOURCE'::text CHECK (route = ANY (ARRAY['A_WITH_SOURCE'::text, 'B_NO_SOURCE'::text])),
  modules jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_summary jsonb,
  validation jsonb NOT NULL DEFAULT '{"checks": [], "automatic_pass": false}'::jsonb,
  qa jsonb NOT NULL DEFAULT '{"status": "PENDING"}'::jsonb,
  state text NOT NULL DEFAULT 'STEP_DRAFT'::text,
  iteration_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT syllabus_pkey PRIMARY KEY (id),
  CONSTRAINT syllabus_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.instructional_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  lesson_plans jsonb NOT NULL DEFAULT '[]'::jsonb,
  blockers jsonb NOT NULL DEFAULT '[]'::jsonb,
  dod jsonb NOT NULL DEFAULT '{"checklist": [], "semantic_checks": [], "automatic_checks": []}'::jsonb,
  approvals jsonb NOT NULL DEFAULT '{"architect_status": "PENDING"}'::jsonb,
  final_status text,
  state text NOT NULL DEFAULT 'STEP_DRAFT'::text,
  iteration_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  validation jsonb,
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT instructional_plans_pkey PRIMARY KEY (id),
  CONSTRAINT instructional_plans_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.system_prompts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  version text NOT NULL DEFAULT '1.0.0'::text,
  content text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  parent_prompt_id uuid,
  source text NOT NULL DEFAULT 'SEED'::text,
  change_summary text,
  created_by uuid,
  scope text NOT NULL DEFAULT 'Cursos'::text,
  CONSTRAINT system_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT system_prompts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT system_prompts_parent_prompt_id_fkey FOREIGN KEY (parent_prompt_id) REFERENCES public.system_prompts(id),
  CONSTRAINT system_prompts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.curation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  attempt_number integer NOT NULL DEFAULT 1 CHECK (attempt_number = ANY (ARRAY[1, 2])),
  state text NOT NULL DEFAULT 'PHASE2_DRAFT'::text,
  qa_decision jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT curation_pkey PRIMARY KEY (id),
  CONSTRAINT curation_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.curation_rows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  curation_id uuid NOT NULL,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  component text NOT NULL,
  is_critical boolean NOT NULL DEFAULT false,
  source_ref text NOT NULL,
  source_title text,
  source_rationale text,
  url_status text NOT NULL DEFAULT 'PENDING'::text,
  http_status_code integer,
  last_checked_at timestamp with time zone,
  failure_reason text,
  apta boolean,
  motivo_no_apta text,
  cobertura_completa boolean,
  notes text,
  auto_evaluated boolean DEFAULT false,
  auto_reason text,
  forbidden_override boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  origin text NOT NULL DEFAULT 'automatic'::text CHECK (origin = ANY (ARRAY['automatic'::text, 'manual'::text])),
  source_kind text NOT NULL DEFAULT 'url'::text CHECK (source_kind = ANY (ARRAY['url'::text, 'pdf'::text])),
  storage_bucket text,
  storage_path text,
  file_name text,
  mime_type text,
  file_size_bytes bigint CHECK (file_size_bytes IS NULL OR file_size_bytes > 0),
  content_sha256 text,
  validation_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  added_by uuid,
  CONSTRAINT curation_rows_pkey PRIMARY KEY (id),
  CONSTRAINT curation_rows_curation_id_fkey FOREIGN KEY (curation_id) REFERENCES public.curation(id),
  CONSTRAINT curation_rows_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.curation_blockers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  curation_id uuid NOT NULL,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  component text NOT NULL,
  impact text NOT NULL,
  owner text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN'::text CHECK (status = ANY (ARRAY['OPEN'::text, 'MITIGATING'::text, 'ACCEPTED'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT curation_blockers_pkey PRIMARY KEY (id),
  CONSTRAINT curation_blockers_curation_id_fkey FOREIGN KEY (curation_id) REFERENCES public.curation(id)
);
CREATE TABLE public.model_settings (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  model_name text NOT NULL DEFAULT 'gemini-2.5-flash'::text,
  temperature numeric NOT NULL DEFAULT 0.70,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  fallback_model text NOT NULL DEFAULT 'gemini-2.5-flash'::text,
  thinking_level text NOT NULL DEFAULT 'medium'::text CHECK (thinking_level = ANY (ARRAY['minimal'::text, 'low'::text, 'medium'::text, 'high'::text])),
  setting_type text DEFAULT 'SEARCH'::text CHECK (setting_type = ANY (ARRAY['ARTIFACT_BASE'::text, 'SYLLABUS'::text, 'INSTRUCTIONAL_PLAN'::text, 'MATERIALS'::text, 'CURATION'::text, 'BUNDLE_AGENT'::text, 'LIA_MODEL'::text, 'LIA MODEL'::text, 'COMPUTER'::text, 'SEARCH'::text, 'LIA_REASONING'::text, 'LIA_COMPUTER_USE'::text])) NOT VALI),
  organization_id uuid,
  scope text NOT NULL DEFAULT 'Cursos'::text,
  CONSTRAINT model_settings_pkey PRIMARY KEY (id),
  CONSTRAINT model_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  version integer NOT NULL DEFAULT 1,
  prompt_version text NOT NULL DEFAULT 'default'::text,
  state text NOT NULL DEFAULT 'PHASE3_DRAFT'::text,
  qa_decision jsonb,
  package jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lessons jsonb DEFAULT '[]'::jsonb,
  global_blockers jsonb DEFAULT '[]'::jsonb,
  dod jsonb DEFAULT '{"checklist": [], "automatic_checks": []}'::jsonb,
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT materials_pkey PRIMARY KEY (id),
  CONSTRAINT materials_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.material_lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  materials_id uuid NOT NULL,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  module_id text NOT NULL,
  module_title text NOT NULL,
  oa_text text NOT NULL,
  expected_components ARRAY NOT NULL DEFAULT '{}'::text[],
  quiz_spec jsonb,
  requires_demo_guide boolean DEFAULT false,
  dod jsonb NOT NULL DEFAULT '{}'::jsonb,
  state text NOT NULL DEFAULT 'PENDING'::text,
  iteration_count integer NOT NULL DEFAULT 0,
  max_iterations integer NOT NULL DEFAULT 5,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT material_lessons_pkey PRIMARY KEY (id),
  CONSTRAINT material_lessons_materials_id_fkey FOREIGN KEY (materials_id) REFERENCES public.materials(id)
);
CREATE TABLE public.material_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_lesson_id uuid NOT NULL,
  type text NOT NULL,
  content jsonb NOT NULL,
  source_refs ARRAY DEFAULT '{}'::text[],
  validation_status text NOT NULL DEFAULT 'PENDING'::text,
  validation_errors ARRAY DEFAULT '{}'::text[],
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  iteration_number integer NOT NULL DEFAULT 1,
  assets jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT material_components_pkey PRIMARY KEY (id),
  CONSTRAINT material_components_material_lesson_id_fkey FOREIGN KEY (material_lesson_id) REFERENCES public.material_lessons(id)
);
CREATE TABLE public.publication_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL UNIQUE,
  category text NOT NULL,
  level text NOT NULL CHECK (level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  instructor_email text NOT NULL,
  thumbnail_url text,
  slug text NOT NULL,
  price numeric DEFAULT 0.00,
  lesson_videos jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'DRAFT'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'READY'::text, 'SENT'::text, 'APPROVED'::text, 'REJECTED'::text])),
  soflia_course_id uuid,
  soflia_response jsonb,
  sent_at timestamp with time zone,
  response_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  selected_lessons jsonb,
  upstream_dirty boolean DEFAULT false,
  upstream_dirty_source text,
  CONSTRAINT publication_requests_pkey PRIMARY KEY (id),
  CONSTRAINT publication_requests_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.scorm_imports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid,
  original_filename text NOT NULL,
  storage_path text NOT NULL,
  scorm_version text,
  manifest_raw jsonb,
  organizations jsonb,
  resources jsonb,
  sco_count integer DEFAULT 0,
  status text DEFAULT 'UPLOADED'::text,
  processing_step text,
  error_message text,
  content_analysis jsonb DEFAULT '{}'::jsonb,
  detected_components jsonb DEFAULT '[]'::jsonb,
  gaps_detected jsonb DEFAULT '[]'::jsonb,
  enrichment_plan jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_by uuid,
  organization_id uuid,
  CONSTRAINT scorm_imports_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_imports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT scorm_imports_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT scorm_imports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.scorm_resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scorm_import_id uuid,
  resource_identifier text NOT NULL,
  scorm_type text,
  href text,
  files jsonb DEFAULT '[]'::jsonb,
  extracted_path text,
  content_type text,
  raw_html text,
  clean_text text,
  word_count integer DEFAULT 0,
  images jsonb DEFAULT '[]'::jsonb,
  videos jsonb DEFAULT '[]'::jsonb,
  documents jsonb DEFAULT '[]'::jsonb,
  has_quiz boolean DEFAULT false,
  quiz_raw jsonb,
  quiz_transformed jsonb,
  mapped_to_lesson_id text,
  material_component_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scorm_resources_pkey PRIMARY KEY (id),
  CONSTRAINT scorm_resources_scorm_import_id_fkey FOREIGN KEY (scorm_import_id) REFERENCES public.scorm_imports(id)
);
CREATE TABLE public.pipeline_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid NOT NULL,
  event_type text NOT NULL,
  event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  step_id text,
  entity_id text,
  entity_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pipeline_events_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_events_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id)
);
CREATE TABLE public.production_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  artifact_id uuid NOT NULL,
  material_lesson_id uuid,
  material_component_id uuid,
  lesson_id text,
  module_id text,
  job_type text NOT NULL,
  provider text NOT NULL,
  provider_model text,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'QUEUED'::text, 'RUNNING'::text, 'WAITING_PROVIDER'::text, 'SUCCEEDED'::text, 'FAILED'::text, 'CANCELLED'::text, 'RETRY_SCHEDULED'::text])),
  idempotency_key text NOT NULL,
  attempt integer NOT NULL DEFAULT 1,
  input_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  progress jsonb NOT NULL DEFAULT '[]'::jsonb,
  provider_request_id text,
  provider_job_id text,
  provider_callback_id text,
  provider_error jsonb,
  estimated_cost_cents integer,
  actual_cost_cents integer,
  duration_seconds integer,
  created_by uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  worker_id uuid,
  claimed_at timestamp with time zone,
  worker_heartbeat_at timestamp with time zone,
  output_checksum text,
  logs_ref text,
  preferred_worker_id uuid,
  lease_expires_at timestamp with time zone,
  assigned_strategy text NOT NULL DEFAULT 'AUTO'::text CHECK (assigned_strategy = ANY (ARRAY['AUTO'::text, 'MANUAL'::text, 'LEGACY'::text])),
  render_batch_id uuid,
  CONSTRAINT production_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT production_jobs_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT production_jobs_material_lesson_id_fkey FOREIGN KEY (material_lesson_id) REFERENCES public.material_lessons(id),
  CONSTRAINT production_jobs_material_component_id_fkey FOREIGN KEY (material_component_id) REFERENCES public.material_components(id),
  CONSTRAINT production_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT production_jobs_preferred_worker_id_fkey FOREIGN KEY (preferred_worker_id) REFERENCES public.render_workers(id),
  CONSTRAINT production_jobs_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.render_workers(id),
  CONSTRAINT production_jobs_render_batch_id_fkey FOREIGN KEY (render_batch_id) REFERENCES public.production_render_batches(id)
);
CREATE TABLE public.production_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  artifact_id uuid NOT NULL,
  production_job_id uuid,
  material_lesson_id uuid,
  material_component_id uuid,
  lesson_id text,
  module_id text,
  asset_type text NOT NULL,
  provider text,
  storage_bucket text,
  storage_path text,
  public_url text,
  external_url text,
  mime_type text,
  file_size_bytes bigint,
  duration_seconds integer,
  checksum text,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  qa_status text NOT NULL DEFAULT 'PENDING'::text CHECK (qa_status = ANY (ARRAY['PENDING'::text, 'GENERATED'::text, 'READY_FOR_QA'::text, 'APPROVED'::text, 'REJECTED'::text, 'EXPORTED'::text, 'PUBLISHED'::text, 'ARCHIVED'::text])),
  qa_notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT production_assets_pkey PRIMARY KEY (id),
  CONSTRAINT production_assets_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT production_assets_production_job_id_fkey FOREIGN KEY (production_job_id) REFERENCES public.production_jobs(id),
  CONSTRAINT production_assets_material_lesson_id_fkey FOREIGN KEY (material_lesson_id) REFERENCES public.material_lessons(id),
  CONSTRAINT production_assets_material_component_id_fkey FOREIGN KEY (material_component_id) REFERENCES public.material_components(id),
  CONSTRAINT production_assets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.remotion_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  description text,
  entry_point text NOT NULL DEFAULT 'index.tsx'::text,
  config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_public boolean NOT NULL DEFAULT false,
  storage_path text,
  thumbnail_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  bundle_status text NOT NULL DEFAULT 'NOT_APPLICABLE'::text CHECK (bundle_status = ANY (ARRAY['NOT_APPLICABLE'::text, 'VALIDATING'::text, 'STORED_REFERENCE'::text, 'PENDING_REVIEW'::text, 'APPROVED'::text, 'APPROVED_FOR_SANDBOX'::text, 'SANDBOX_VALIDATION_FAILED'::text, 'REJECTED'::text])),
  composition_id text,
  CONSTRAINT remotion_templates_pkey PRIMARY KEY (id),
  CONSTRAINT remotion_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_acquired_templates (
  organization_id uuid NOT NULL,
  template_id uuid NOT NULL,
  acquired_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_acquired_templates_pkey PRIMARY KEY (organization_id, template_id),
  CONSTRAINT organization_acquired_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_acquired_templates_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id)
);
CREATE TABLE public.user_cloud_storage_credentials (
  user_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['google_drive'::text, 'onedrive'::text, 'heygen'::text])),
  account_email text NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  scopes ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  CONSTRAINT user_cloud_storage_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT user_cloud_storage_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_cloud_storage_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.remotion_template_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  version_number integer NOT NULL,
  status text NOT NULL DEFAULT 'UPLOADED'::text CHECK (status = ANY (ARRAY['UPLOADED'::text, 'VALIDATING'::text, 'VALIDATION_FAILED'::text, 'PENDING_REVIEW'::text, 'APPROVED'::text, 'APPROVED_FOR_SANDBOX'::text, 'SANDBOX_VALIDATION_FAILED'::text, 'REJECTED'::text, 'DEPRECATED'::text])),
  storage_path text NOT NULL,
  original_file_name text,
  bundle_hash text,
  entry_point text,
  manifest jsonb,
  validation_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  validated_at timestamp with time zone,
  approved_at timestamp with time zone,
  approved_by uuid,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  rejection_reason text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  template_type text NOT NULL DEFAULT 'custom_bundle'::text CHECK (template_type = ANY (ARRAY['simple'::text, 'custom_bundle'::text])),
  export_mode text NOT NULL DEFAULT 'component'::text CHECK (export_mode = ANY (ARRAY['component'::text, 'root'::text])),
  composition_id text,
  composition_ids jsonb,
  props_schema jsonb,
  default_props jsonb,
  default_duration_frames integer,
  default_fps integer,
  default_width integer,
  default_height integer,
  build_status text NOT NULL DEFAULT 'PENDING'::text CHECK (build_status = ANY (ARRAY['PENDING'::text, 'BUILDING'::text, 'BUILT'::text, 'BUILD_FAILED'::text])),
  build_hash text,
  build_output_path text,
  built_at timestamp with time zone,
  editable_layers jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT remotion_template_versions_pkey PRIMARY KEY (id),
  CONSTRAINT remotion_template_versions_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id),
  CONSTRAINT remotion_template_versions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT remotion_template_versions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT remotion_template_versions_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.profiles(id),
  CONSTRAINT remotion_template_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  platform_role USER-DEFINED NOT NULL DEFAULT 'CONSTRUCTOR'::app_role,
  source text NOT NULL DEFAULT 'courseforge'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT organization_user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.remotion_template_builds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_version_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'BUILDING'::text CHECK (status = ANY (ARRAY['BUILDING'::text, 'BUILT'::text, 'BUILD_FAILED'::text])),
  bundle_hash text NOT NULL,
  build_hash text,
  entrypoint_path text,
  generated_entrypoint_path text,
  serve_url text,
  build_output_storage_path text,
  composition_id text,
  composition_ids jsonb,
  export_mode text NOT NULL DEFAULT 'component'::text CHECK (export_mode = ANY (ARRAY['component'::text, 'root'::text])),
  build_log text,
  built_at timestamp with time zone,
  build_failed_at timestamp with time zone,
  build_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  cloud_provider text,
  source_storage_path text,
  site_name text,
  region text,
  build_log_storage_path text,
  security_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  provider_build_id text,
  provider_status text,
  provider_status_detail text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  worker_id uuid,
  claimed_at timestamp with time zone,
  worker_heartbeat_at timestamp with time zone,
  lease_expires_at timestamp with time zone,
  output_checksum text,
  CONSTRAINT remotion_template_builds_pkey PRIMARY KEY (id),
  CONSTRAINT remotion_template_builds_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.render_workers(id),
  CONSTRAINT remotion_template_builds_template_version_id_fkey FOREIGN KEY (template_version_id) REFERENCES public.remotion_template_versions(id),
  CONSTRAINT remotion_template_builds_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.soflia_bundle_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by uuid,
  template_id uuid,
  status text NOT NULL DEFAULT 'DRAFTING'::text CHECK (status = ANY (ARRAY['DRAFTING'::text, 'READY_FOR_GENERATION'::text, 'GENERATING'::text, 'VERSION_PENDING_REVIEW'::text, 'ACTIVE'::text, 'ARCHIVED'::text, 'FAILED'::text])),
  title text NOT NULL DEFAULT 'SofLIA Remotion bundle'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  artifact_kind text NOT NULL DEFAULT 'video_bundle'::text CHECK (artifact_kind = ANY (ARRAY['video_bundle'::text, 'slide_template'::text])),
  CONSTRAINT soflia_bundle_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT soflia_bundle_conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT soflia_bundle_conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT soflia_bundle_conversations_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id)
);
CREATE TABLE public.soflia_bundle_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['USER'::text, 'ASSISTANT'::text, 'SYSTEM'::text, 'TOOL'::text])),
  content_redacted text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT soflia_bundle_messages_pkey PRIMARY KEY (id),
  CONSTRAINT soflia_bundle_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.soflia_bundle_conversations(id),
  CONSTRAINT soflia_bundle_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT soflia_bundle_messages_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.soflia_bundle_specs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  version_number integer NOT NULL,
  spec_json jsonb NOT NULL,
  spec_hash text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT soflia_bundle_specs_pkey PRIMARY KEY (id),
  CONSTRAINT soflia_bundle_specs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.soflia_bundle_conversations(id),
  CONSTRAINT soflia_bundle_specs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT soflia_bundle_specs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.soflia_bundle_generation_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  spec_id uuid,
  template_id uuid,
  status text NOT NULL DEFAULT 'QUEUED'::text CHECK (status = ANY (ARRAY['QUEUED'::text, 'RUNNING'::text, 'PACKAGED'::text, 'VALIDATION_FAILED'::text, 'SUBMITTED_FOR_REVIEW'::text, 'FAILED'::text])),
  model text,
  input_hash text,
  output_hash text,
  bundle_storage_path text,
  validation_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_sanitized text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  design_plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  visual_fingerprint jsonb,
  similarity_guard_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT soflia_bundle_generation_runs_pkey PRIMARY KEY (id),
  CONSTRAINT soflia_bundle_generation_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT soflia_bundle_generation_runs_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES public.soflia_bundle_specs(id),
  CONSTRAINT soflia_bundle_generation_runs_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id),
  CONSTRAINT soflia_bundle_generation_runs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.soflia_bundle_conversations(id)
);
CREATE TABLE public.soflia_bundle_version_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  generation_run_id uuid NOT NULL,
  template_version_id uuid NOT NULL UNIQUE,
  parent_template_version_id uuid,
  change_summary text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT soflia_bundle_version_links_pkey PRIMARY KEY (id),
  CONSTRAINT soflia_bundle_version_links_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.soflia_bundle_conversations(id),
  CONSTRAINT soflia_bundle_version_links_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT soflia_bundle_version_links_generation_run_id_fkey FOREIGN KEY (generation_run_id) REFERENCES public.soflia_bundle_generation_runs(id),
  CONSTRAINT soflia_bundle_version_links_template_version_id_fkey FOREIGN KEY (template_version_id) REFERENCES public.remotion_template_versions(id),
  CONSTRAINT soflia_bundle_version_links_parent_template_version_id_fkey FOREIGN KEY (parent_template_version_id) REFERENCES public.remotion_template_versions(id)
);
CREATE TABLE public.render_workers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  device_name text NOT NULL,
  platform text,
  arch text,
  app_version text,
  token_hash text NOT NULL UNIQUE,
  token_last4 text NOT NULL,
  status text NOT NULL DEFAULT 'LINKED'::text CHECK (status = ANY (ARRAY['LINKED'::text, 'ONLINE'::text, 'BUSY'::text, 'OFFLINE'::text, 'REVOKED'::text])),
  last_heartbeat_at timestamp with time zone,
  revoked_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  max_concurrent_jobs integer NOT NULL DEFAULT 1 CHECK (max_concurrent_jobs >= 1 AND max_concurrent_jobs <= 8),
  capabilities jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_capacity_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  capacity_updated_at timestamp with time zone,
  CONSTRAINT render_workers_pkey PRIMARY KEY (id),
  CONSTRAINT render_workers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.render_worker_link_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by uuid,
  code_hash text NOT NULL UNIQUE,
  code_last4 text NOT NULL,
  device_name text,
  platform text,
  arch text,
  app_version text,
  expires_at timestamp with time zone NOT NULL,
  consumed_at timestamp with time zone,
  consumed_by_worker_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT render_worker_link_codes_pkey PRIMARY KEY (id),
  CONSTRAINT render_worker_link_codes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT render_worker_link_codes_consumed_by_worker_id_fkey FOREIGN KEY (consumed_by_worker_id) REFERENCES public.render_workers(id)
);
CREATE TABLE public.production_render_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  artifact_id uuid,
  created_by uuid,
  status text NOT NULL DEFAULT 'QUEUED'::text CHECK (status = ANY (ARRAY['QUEUED'::text, 'RUNNING'::text, 'SUCCEEDED'::text, 'PARTIAL_FAILED'::text, 'FAILED'::text, 'CANCELLED'::text])),
  assignment_mode text NOT NULL DEFAULT 'AUTO'::text CHECK (assignment_mode = ANY (ARRAY['AUTO'::text, 'MANUAL'::text, 'MIXED'::text])),
  default_template_id uuid,
  total_items integer NOT NULL DEFAULT 0,
  completed_items integer NOT NULL DEFAULT 0,
  failed_items integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT production_render_batches_pkey PRIMARY KEY (id),
  CONSTRAINT production_render_batches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT production_render_batches_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT production_render_batches_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT production_render_batches_default_template_id_fkey FOREIGN KEY (default_template_id) REFERENCES public.remotion_templates(id)
);
CREATE TABLE public.production_render_batch_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  artifact_id uuid,
  material_component_id uuid NOT NULL,
  template_id uuid,
  preferred_worker_id uuid,
  production_job_id uuid,
  status text NOT NULL DEFAULT 'QUEUED'::text CHECK (status = ANY (ARRAY['QUEUED'::text, 'WAITING_PROVIDER'::text, 'RUNNING'::text, 'SUCCEEDED'::text, 'FAILED'::text, 'CANCELLED'::text])),
  error_sanitized text,
  variables jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT production_render_batch_items_pkey PRIMARY KEY (id),
  CONSTRAINT production_render_batch_items_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.production_render_batches(id),
  CONSTRAINT production_render_batch_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT production_render_batch_items_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT production_render_batch_items_material_component_id_fkey FOREIGN KEY (material_component_id) REFERENCES public.material_components(id),
  CONSTRAINT production_render_batch_items_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id),
  CONSTRAINT production_render_batch_items_preferred_worker_id_fkey FOREIGN KEY (preferred_worker_id) REFERENCES public.render_workers(id),
  CONSTRAINT production_render_batch_items_production_job_id_fkey FOREIGN KEY (production_job_id) REFERENCES public.production_jobs(id)
);
CREATE TABLE public.remotion_template_previews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  template_id uuid NOT NULL,
  template_version_id uuid NOT NULL,
  template_build_id uuid NOT NULL,
  material_component_id uuid,
  status text NOT NULL DEFAULT 'QUEUED'::text CHECK (status = ANY (ARRAY['QUEUED'::text, 'RUNNING'::text, 'SUCCEEDED'::text, 'FAILED'::text, 'CANCELLED'::text])),
  props_hash text NOT NULL,
  layout_overrides_hash text,
  resolved_props jsonb NOT NULL DEFAULT '{}'::jsonb,
  composition_id text NOT NULL,
  bundle_hash text,
  build_hash text,
  preview_frame integer NOT NULL DEFAULT 0,
  preview_poster_storage_path text,
  preview_video_storage_path text,
  preview_duration_seconds integer,
  preview_frames integer,
  worker_id uuid,
  claimed_at timestamp with time zone,
  worker_heartbeat_at timestamp with time zone,
  lease_expires_at timestamp with time zone,
  provider_status text,
  provider_status_detail text,
  progress jsonb NOT NULL DEFAULT '[]'::jsonb,
  output_checksum text,
  error_code text,
  error_message text,
  requested_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  preview_cache_key text NOT NULL,
  CONSTRAINT remotion_template_previews_pkey PRIMARY KEY (id),
  CONSTRAINT remotion_template_previews_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT remotion_template_previews_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.remotion_templates(id),
  CONSTRAINT remotion_template_previews_template_version_id_fkey FOREIGN KEY (template_version_id) REFERENCES public.remotion_template_versions(id),
  CONSTRAINT remotion_template_previews_template_build_id_fkey FOREIGN KEY (template_build_id) REFERENCES public.remotion_template_builds(id),
  CONSTRAINT remotion_template_previews_material_component_id_fkey FOREIGN KEY (material_component_id) REFERENCES public.material_components(id),
  CONSTRAINT remotion_template_previews_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.render_workers(id),
  CONSTRAINT remotion_template_previews_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.render_worker_job_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  local_run_id text NOT NULL,
  remote_table text NOT NULL CHECK (remote_table = ANY (ARRAY['production_jobs'::text, 'remotion_template_builds'::text, 'remotion_template_previews'::text])),
  remote_job_id uuid NOT NULL,
  job_type text NOT NULL CHECK (job_type = ANY (ARRAY['render'::text, 'template_build'::text, 'template_preview'::text])),
  production_job_id uuid,
  template_build_id uuid,
  template_preview_id uuid,
  related_template_build_id uuid,
  render_batch_id uuid,
  artifact_id uuid,
  material_component_id uuid,
  template_version_id uuid,
  composition_id text,
  bundle_hash text,
  props_hash text,
  output_storage_path text,
  status text NOT NULL DEFAULT 'running'::text CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'upload_pending'::text, 'confirm_pending'::text, 'failed'::text, 'interrupted'::text])),
  started_at timestamp with time zone NOT NULL,
  finished_at timestamp with time zone,
  elapsed_ms bigint,
  last_stage text,
  last_progress_percent numeric,
  power_profile text,
  max_concurrent_jobs integer,
  render_concurrency integer,
  hardware_acceleration text,
  chromium_gl text,
  video_bitrate text,
  platform text NOT NULL,
  arch text NOT NULL,
  cpu_model text,
  cpu_logical_threads integer NOT NULL CHECK (cpu_logical_threads >= 1),
  memory_total_bytes bigint NOT NULL CHECK (memory_total_bytes >= 0),
  gpu_adapters jsonb NOT NULL DEFAULT '[]'::jsonb,
  config_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  hardware_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  sample_count integer NOT NULL DEFAULT 0 CHECK (sample_count >= 0),
  avg_app_cpu_percent numeric NOT NULL DEFAULT 0,
  max_app_cpu_percent numeric NOT NULL DEFAULT 0,
  avg_app_gpu_percent numeric NOT NULL DEFAULT 0,
  max_app_gpu_percent numeric NOT NULL DEFAULT 0,
  avg_app_memory_bytes bigint NOT NULL DEFAULT 0,
  max_app_memory_bytes bigint NOT NULL DEFAULT 0,
  avg_system_cpu_percent numeric NOT NULL DEFAULT 0,
  max_system_cpu_percent numeric NOT NULL DEFAULT 0,
  avg_system_gpu_percent numeric NOT NULL DEFAULT 0,
  max_system_gpu_percent numeric NOT NULL DEFAULT 0,
  max_system_memory_used_bytes bigint NOT NULL DEFAULT 0,
  error_code text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT render_worker_job_runs_pkey PRIMARY KEY (id),
  CONSTRAINT render_worker_job_runs_worker_fkey FOREIGN KEY (worker_id) REFERENCES public.render_workers(id),
  CONSTRAINT render_worker_job_runs_organization_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT render_worker_job_runs_production_job_fkey FOREIGN KEY (production_job_id) REFERENCES public.production_jobs(id),
  CONSTRAINT render_worker_job_runs_template_build_fkey FOREIGN KEY (template_build_id) REFERENCES public.remotion_template_builds(id),
  CONSTRAINT render_worker_job_runs_template_preview_fkey FOREIGN KEY (template_preview_id) REFERENCES public.remotion_template_previews(id),
  CONSTRAINT render_worker_job_runs_related_template_build_fkey FOREIGN KEY (related_template_build_id) REFERENCES public.remotion_template_builds(id),
  CONSTRAINT render_worker_job_runs_render_batch_fkey FOREIGN KEY (render_batch_id) REFERENCES public.production_render_batches(id),
  CONSTRAINT render_worker_job_runs_artifact_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT render_worker_job_runs_material_component_fkey FOREIGN KEY (material_component_id) REFERENCES public.material_components(id),
  CONSTRAINT render_worker_job_runs_template_version_fkey FOREIGN KEY (template_version_id) REFERENCES public.remotion_template_versions(id)
);
CREATE TABLE public.render_worker_job_metric_samples (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  run_id uuid NOT NULL,
  worker_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  remote_table text NOT NULL,
  remote_job_id uuid NOT NULL,
  sampled_at timestamp with time zone NOT NULL,
  worker_state text NOT NULL,
  stage text,
  progress_percent numeric,
  app_cpu_percent numeric NOT NULL DEFAULT 0,
  app_gpu_percent numeric NOT NULL DEFAULT 0,
  app_memory_bytes bigint NOT NULL DEFAULT 0,
  app_process_count integer NOT NULL DEFAULT 0,
  system_cpu_percent numeric NOT NULL DEFAULT 0,
  system_gpu_percent numeric NOT NULL DEFAULT 0,
  system_memory_used_bytes bigint NOT NULL DEFAULT 0,
  system_memory_total_bytes bigint NOT NULL DEFAULT 0,
  system_cpu_count integer NOT NULL DEFAULT 0,
  top_processes jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  system_top_processes jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT render_worker_job_metric_samples_pkey PRIMARY KEY (id),
  CONSTRAINT render_worker_job_metric_samples_organization_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT render_worker_job_metric_samples_run_fkey FOREIGN KEY (run_id) REFERENCES public.render_worker_job_runs(id),
  CONSTRAINT render_worker_job_metric_samples_worker_fkey FOREIGN KEY (worker_id) REFERENCES public.render_workers(id)
);
CREATE TABLE public.heygen_workspace_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  account_label text,
  api_key_secret_ref text,
  api_key_last4 text,
  default_callback_url text,
  webhook_endpoint_id text,
  webhook_secret_ref text,
  last_sync_status text NOT NULL DEFAULT 'NEVER_SYNCED'::text CHECK (last_sync_status = ANY (ARRAY['NEVER_SYNCED'::text, 'SUCCEEDED'::text, 'FAILED'::text])),
  last_sync_error text,
  last_synced_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT heygen_workspace_connections_pkey PRIMARY KEY (id),
  CONSTRAINT heygen_workspace_connections_organization_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.heygen_avatar_presets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  heygen_avatar_group_id text,
  heygen_avatar_look_id text NOT NULL,
  name text NOT NULL,
  avatar_type text,
  default_voice_id text,
  supported_api_engines jsonb NOT NULL DEFAULT '[]'::jsonb,
  preview_image_url text,
  preview_video_url text,
  status text,
  is_default boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT heygen_avatar_presets_pkey PRIMARY KEY (id),
  CONSTRAINT heygen_avatar_presets_organization_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.heygen_voice_presets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  heygen_voice_id text NOT NULL,
  name text NOT NULL,
  language text,
  gender text,
  voice_type text,
  preview_audio_url text,
  is_default boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT heygen_voice_presets_pkey PRIMARY KEY (id),
  CONSTRAINT heygen_voice_presets_organization_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.production_provider_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = 'heygen'::text),
  encrypted_secret text NOT NULL,
  secret_last4 text CHECK (secret_last4 IS NULL OR char_length(secret_last4) <= 8),
  status text NOT NULL DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'REVOKED'::text])),
  validation_status text NOT NULL DEFAULT 'NEVER_VALIDATED'::text CHECK (validation_status = ANY (ARRAY['NEVER_VALIDATED'::text, 'VALID'::text, 'INVALID'::text])),
  last_validated_at timestamp with time zone,
  last_validation_error text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT production_provider_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT production_provider_credentials_organization_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.standalone_assembly_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  created_by uuid,
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'DRAFT'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'READY'::text, 'RENDERING'::text, 'COMPLETED'::text, 'FAILED'::text, 'ARCHIVED'::text])),
  final_video_url text,
  backing_artifact_id uuid,
  backing_material_id uuid,
  backing_lesson_id uuid,
  backing_component_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT standalone_assembly_projects_pkey PRIMARY KEY (id),
  CONSTRAINT standalone_assembly_projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT standalone_assembly_projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT standalone_assembly_projects_backing_artifact_id_fkey FOREIGN KEY (backing_artifact_id) REFERENCES public.artifacts(id),
  CONSTRAINT standalone_assembly_projects_backing_material_id_fkey FOREIGN KEY (backing_material_id) REFERENCES public.materials(id),
  CONSTRAINT standalone_assembly_projects_backing_lesson_id_fkey FOREIGN KEY (backing_lesson_id) REFERENCES public.material_lessons(id),
  CONSTRAINT standalone_assembly_projects_backing_component_id_fkey FOREIGN KEY (backing_component_id) REFERENCES public.material_components(id)
);