export const REVIEWER_PLATFORM_ROLES = [
  "ADMIN",
  "ARQUITECTO",
  "SUPERADMIN",
] as const;

export const REVIEWER_ROLE_SET = new Set<string>(REVIEWER_PLATFORM_ROLES);

export const SYLLABUS_STATES = {
  DRAFT: "STEP_DRAFT",
  GENERATING: "STEP_GENERATING",
  READY_FOR_QA: "STEP_READY_FOR_QA",
  APPROVED: "STEP_APPROVED",
  REJECTED: "STEP_REJECTED",
} as const;

export const PLAN_STATES = {
  PROCESSING: "STEP_PROCESSING",
  READY_FOR_REVIEW: "STEP_READY_FOR_REVIEW",
  APPROVED: "STEP_APPROVED",
  REJECTED: "STEP_REJECTED",
  FAILED: "STEP_FAILED",
  WITH_BLOCKERS: "STEP_WITH_BLOCKERS",
} as const;

export const PLAN_TERMINAL_STATES = new Set<string>([
  PLAN_STATES.READY_FOR_REVIEW,
  PLAN_STATES.APPROVED,
  PLAN_STATES.REJECTED,
  PLAN_STATES.FAILED,
]);

export const CURATION_STATES = {
  GENERATING: "PHASE2_GENERATING",
  READY_FOR_QA: "PHASE2_READY_FOR_QA",
  APPROVED: "PHASE2_APPROVED",
  REJECTED: "PHASE2_REJECTED",
  BLOCKED: "PHASE2_BLOCKED",
  PAUSED: "PAUSED",
  PAUSED_REQUESTED: "PAUSED_REQUESTED",
  STOPPED: "STOPPED",
  STOPPED_REQUESTED: "STOPPED_REQUESTED",
} as const;

export const CURATION_RUNNING_STATES = new Set<string>([
  CURATION_STATES.GENERATING,
  CURATION_STATES.PAUSED_REQUESTED,
  CURATION_STATES.STOPPED_REQUESTED,
]);

export const MATERIALS_STATES = {
  DRAFT: "PHASE3_DRAFT",
  GENERATING: "PHASE3_GENERATING",
  NEEDS_FIX: "PHASE3_NEEDS_FIX",
  READY_FOR_QA: "PHASE3_READY_FOR_QA",
  APPROVED: "PHASE3_APPROVED",
  REJECTED: "PHASE3_REJECTED",
} as const;
